// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnswerByProto.proto

package com.jk.jkproject.net.im.info;

public final class AnswerByProto {
  private AnswerByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnswerByProtoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AnswerByProtoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    String getUserId();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *类型 1同意 2取消
     * </pre>
     *
     * <code>optional int32 type = 2;</code>
     */
    int getType();

    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 3;</code>
     */
    String getStreamId();
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 3;</code>
     */
    com.google.protobuf.ByteString
        getStreamIdBytes();

    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 4;</code>
     */
    String getRoomId();
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 4;</code>
     */
    com.google.protobuf.ByteString
        getRoomIdBytes();
  }
  /**
   * Protobuf type {@code proto.AnswerByProtoReq}
   */
  public  static final class AnswerByProtoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AnswerByProtoReq)
      AnswerByProtoReqOrBuilder {
    // Use AnswerByProtoReq.newBuilder() to construct.
    private AnswerByProtoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnswerByProtoReq() {
      userId_ = "";
      type_ = 0;
      streamId_ = "";
      roomId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AnswerByProtoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              streamId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              roomId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnswerByProto.internal_static_proto_AnswerByProtoReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnswerByProto.internal_static_proto_AnswerByProtoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnswerByProto.AnswerByProtoReq.class, AnswerByProto.AnswerByProtoReq.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *类型 1同意 2取消
     * </pre>
     *
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int STREAMID_FIELD_NUMBER = 3;
    private volatile Object streamId_;
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 3;</code>
     */
    public String getStreamId() {
      Object ref = streamId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        streamId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStreamIdBytes() {
      Object ref = streamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        streamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMID_FIELD_NUMBER = 4;
    private volatile Object roomId_;
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 4;</code>
     */
    public String getRoomId() {
      Object ref = roomId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (!getStreamIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, streamId_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, roomId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (!getStreamIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, streamId_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, roomId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnswerByProto.AnswerByProtoReq)) {
        return super.equals(obj);
      }
      AnswerByProto.AnswerByProtoReq other = (AnswerByProto.AnswerByProtoReq) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (getType()
          == other.getType());
      result = result && getStreamId()
          .equals(other.getStreamId());
      result = result && getRoomId()
          .equals(other.getRoomId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + STREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getStreamId().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnswerByProto.AnswerByProtoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnswerByProto.AnswerByProtoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AnswerByProtoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AnswerByProtoReq)
        AnswerByProto.AnswerByProtoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnswerByProto.internal_static_proto_AnswerByProtoReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnswerByProto.internal_static_proto_AnswerByProtoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnswerByProto.AnswerByProtoReq.class, AnswerByProto.AnswerByProtoReq.Builder.class);
      }

      // Construct using AnswerByProto.AnswerByProtoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        type_ = 0;

        streamId_ = "";

        roomId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnswerByProto.internal_static_proto_AnswerByProtoReq_descriptor;
      }

      public AnswerByProto.AnswerByProtoReq getDefaultInstanceForType() {
        return AnswerByProto.AnswerByProtoReq.getDefaultInstance();
      }

      public AnswerByProto.AnswerByProtoReq build() {
        AnswerByProto.AnswerByProtoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AnswerByProto.AnswerByProtoReq buildPartial() {
        AnswerByProto.AnswerByProtoReq result = new AnswerByProto.AnswerByProtoReq(this);
        result.userId_ = userId_;
        result.type_ = type_;
        result.streamId_ = streamId_;
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnswerByProto.AnswerByProtoReq) {
          return mergeFrom((AnswerByProto.AnswerByProtoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnswerByProto.AnswerByProtoReq other) {
        if (other == AnswerByProto.AnswerByProtoReq.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getStreamId().isEmpty()) {
          streamId_ = other.streamId_;
          onChanged();
        }
        if (!other.getRoomId().isEmpty()) {
          roomId_ = other.roomId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnswerByProto.AnswerByProtoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnswerByProto.AnswerByProtoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *类型 1同意 2取消
       * </pre>
       *
       * <code>optional int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *类型 1同意 2取消
       * </pre>
       *
       * <code>optional int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型 1同意 2取消
       * </pre>
       *
       * <code>optional int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object streamId_ = "";
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 3;</code>
       */
      public String getStreamId() {
        Object ref = streamId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          streamId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStreamIdBytes() {
        Object ref = streamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          streamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 3;</code>
       */
      public Builder setStreamId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 3;</code>
       */
      public Builder clearStreamId() {
        
        streamId_ = getDefaultInstance().getStreamId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 3;</code>
       */
      public Builder setStreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streamId_ = value;
        onChanged();
        return this;
      }

      private Object roomId_ = "";
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 4;</code>
       */
      public String getRoomId() {
        Object ref = roomId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roomId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes() {
        Object ref = roomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 4;</code>
       */
      public Builder setRoomId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 4;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = getDefaultInstance().getRoomId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 4;</code>
       */
      public Builder setRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.AnswerByProtoReq)
    }

    // @@protoc_insertion_point(class_scope:proto.AnswerByProtoReq)
    private static final AnswerByProto.AnswerByProtoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnswerByProto.AnswerByProtoReq();
    }

    public static AnswerByProto.AnswerByProtoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnswerByProtoReq>
        PARSER = new com.google.protobuf.AbstractParser<AnswerByProtoReq>() {
      public AnswerByProtoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnswerByProtoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnswerByProtoReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AnswerByProtoReq> getParserForType() {
      return PARSER;
    }

    public AnswerByProto.AnswerByProtoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnswerByProtoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AnswerByProtoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsg getMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsgOrBuilder getMsgOrBuilder();

    /**
     * <pre>
     *主播取消的用户id
     * </pre>
     *
     * <code>optional string userId = 2;</code>
     */
    String getUserId();
    /**
     * <pre>
     *主播取消的用户id
     * </pre>
     *
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code proto.AnswerByProtoRes}
   */
  public  static final class AnswerByProtoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AnswerByProtoRes)
      AnswerByProtoResOrBuilder {
    // Use AnswerByProtoRes.newBuilder() to construct.
    private AnswerByProtoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnswerByProtoRes() {
      userId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AnswerByProtoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Entity.ReturnMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(Entity.ReturnMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnswerByProto.internal_static_proto_AnswerByProtoRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnswerByProto.internal_static_proto_AnswerByProtoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnswerByProto.AnswerByProtoRes.class, AnswerByProto.AnswerByProtoRes.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private Entity.ReturnMsg msg_;
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsg getMsg() {
      return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <pre>
     *主播取消的用户id
     * </pre>
     *
     * <code>optional string userId = 2;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *主播取消的用户id
     * </pre>
     *
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnswerByProto.AnswerByProtoRes)) {
        return super.equals(obj);
      }
      AnswerByProto.AnswerByProtoRes other = (AnswerByProto.AnswerByProtoRes) obj;

      boolean result = true;
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && getUserId()
          .equals(other.getUserId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnswerByProto.AnswerByProtoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnswerByProto.AnswerByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnswerByProto.AnswerByProtoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AnswerByProtoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AnswerByProtoRes)
        AnswerByProto.AnswerByProtoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnswerByProto.internal_static_proto_AnswerByProtoRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnswerByProto.internal_static_proto_AnswerByProtoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnswerByProto.AnswerByProtoRes.class, AnswerByProto.AnswerByProtoRes.Builder.class);
      }

      // Construct using AnswerByProto.AnswerByProtoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        userId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnswerByProto.internal_static_proto_AnswerByProtoRes_descriptor;
      }

      public AnswerByProto.AnswerByProtoRes getDefaultInstanceForType() {
        return AnswerByProto.AnswerByProtoRes.getDefaultInstance();
      }

      public AnswerByProto.AnswerByProtoRes build() {
        AnswerByProto.AnswerByProtoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AnswerByProto.AnswerByProtoRes buildPartial() {
        AnswerByProto.AnswerByProtoRes result = new AnswerByProto.AnswerByProtoRes(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnswerByProto.AnswerByProtoRes) {
          return mergeFrom((AnswerByProto.AnswerByProtoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnswerByProto.AnswerByProtoRes other) {
        if (other == AnswerByProto.AnswerByProtoRes.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnswerByProto.AnswerByProtoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnswerByProto.AnswerByProtoRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Entity.ReturnMsg msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> msgBuilder_;
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(
          Entity.ReturnMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder mergeMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              Entity.ReturnMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              Entity.ReturnMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *主播取消的用户id
       * </pre>
       *
       * <code>optional string userId = 2;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *主播取消的用户id
       * </pre>
       *
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *主播取消的用户id
       * </pre>
       *
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主播取消的用户id
       * </pre>
       *
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主播取消的用户id
       * </pre>
       *
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.AnswerByProtoRes)
    }

    // @@protoc_insertion_point(class_scope:proto.AnswerByProtoRes)
    private static final AnswerByProto.AnswerByProtoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnswerByProto.AnswerByProtoRes();
    }

    public static AnswerByProto.AnswerByProtoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnswerByProtoRes>
        PARSER = new com.google.protobuf.AbstractParser<AnswerByProtoRes>() {
      public AnswerByProtoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnswerByProtoRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnswerByProtoRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AnswerByProtoRes> getParserForType() {
      return PARSER;
    }

    public AnswerByProto.AnswerByProtoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AnswerByProtoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AnswerByProtoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AnswerByProtoRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AnswerByProtoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023AnswerByProto.proto\022\005proto\032\014Entity.pro" +
      "to\"R\n\020AnswerByProtoReq\022\016\n\006userId\030\001 \001(\t\022\014" +
      "\n\004type\030\002 \001(\005\022\020\n\010streamId\030\003 \001(\t\022\016\n\006roomId" +
      "\030\004 \001(\t\"A\n\020AnswerByProtoRes\022\035\n\003msg\030\001 \001(\0132" +
      "\020.proto.ReturnMsg\022\016\n\006userId\030\002 \001(\tB \n\036com" +
      ".sencorsta.ids.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_AnswerByProtoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_AnswerByProtoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AnswerByProtoReq_descriptor,
        new String[] { "UserId", "Type", "StreamId", "RoomId", });
    internal_static_proto_AnswerByProtoRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_AnswerByProtoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AnswerByProtoRes_descriptor,
        new String[] { "Msg", "UserId", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
