// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CancelPKByProto.proto

package com.jk.jkproject.net.im.info;

public final class CancelPKByProto {
  private CancelPKByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CancelPKByProtoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CancelPKByProtoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    String getPkId();
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPkIdBytes();

    /**
     * <pre>
     *对方的房间Id
     * </pre>
     *
     * <code>optional string tagRoomId = 2;</code>
     */
    String getTagRoomId();
    /**
     * <pre>
     *对方的房间Id
     * </pre>
     *
     * <code>optional string tagRoomId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTagRoomIdBytes();

    /**
     * <pre>
     *自己的房间Id
     * </pre>
     *
     * <code>optional string myRoomId = 3;</code>
     */
    String getMyRoomId();
    /**
     * <pre>
     *自己的房间Id
     * </pre>
     *
     * <code>optional string myRoomId = 3;</code>
     */
    com.google.protobuf.ByteString
        getMyRoomIdBytes();

    /**
     * <pre>
     *对方主播Id
     * </pre>
     *
     * <code>optional string tagUserId = 4;</code>
     */
    String getTagUserId();
    /**
     * <pre>
     *对方主播Id
     * </pre>
     *
     * <code>optional string tagUserId = 4;</code>
     */
    com.google.protobuf.ByteString
        getTagUserIdBytes();
  }
  /**
   * Protobuf type {@code proto.CancelPKByProtoReq}
   */
  public  static final class CancelPKByProtoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CancelPKByProtoReq)
      CancelPKByProtoReqOrBuilder {
    // Use CancelPKByProtoReq.newBuilder() to construct.
    private CancelPKByProtoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CancelPKByProtoReq() {
      pkId_ = "";
      tagRoomId_ = "";
      myRoomId_ = "";
      tagUserId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CancelPKByProtoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              pkId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              tagRoomId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              myRoomId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              tagUserId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CancelPKByProto.internal_static_proto_CancelPKByProtoReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CancelPKByProto.internal_static_proto_CancelPKByProtoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CancelPKByProto.CancelPKByProtoReq.class, CancelPKByProto.CancelPKByProtoReq.Builder.class);
    }

    public static final int PKID_FIELD_NUMBER = 1;
    private volatile Object pkId_;
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    public String getPkId() {
      Object ref = pkId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pkId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPkIdBytes() {
      Object ref = pkId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGROOMID_FIELD_NUMBER = 2;
    private volatile Object tagRoomId_;
    /**
     * <pre>
     *对方的房间Id
     * </pre>
     *
     * <code>optional string tagRoomId = 2;</code>
     */
    public String getTagRoomId() {
      Object ref = tagRoomId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagRoomId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对方的房间Id
     * </pre>
     *
     * <code>optional string tagRoomId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTagRoomIdBytes() {
      Object ref = tagRoomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tagRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MYROOMID_FIELD_NUMBER = 3;
    private volatile Object myRoomId_;
    /**
     * <pre>
     *自己的房间Id
     * </pre>
     *
     * <code>optional string myRoomId = 3;</code>
     */
    public String getMyRoomId() {
      Object ref = myRoomId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        myRoomId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *自己的房间Id
     * </pre>
     *
     * <code>optional string myRoomId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMyRoomIdBytes() {
      Object ref = myRoomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        myRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGUSERID_FIELD_NUMBER = 4;
    private volatile Object tagUserId_;
    /**
     * <pre>
     *对方主播Id
     * </pre>
     *
     * <code>optional string tagUserId = 4;</code>
     */
    public String getTagUserId() {
      Object ref = tagUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对方主播Id
     * </pre>
     *
     * <code>optional string tagUserId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTagUserIdBytes() {
      Object ref = tagUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tagUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPkIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pkId_);
      }
      if (!getTagRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tagRoomId_);
      }
      if (!getMyRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, myRoomId_);
      }
      if (!getTagUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tagUserId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPkIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pkId_);
      }
      if (!getTagRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tagRoomId_);
      }
      if (!getMyRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, myRoomId_);
      }
      if (!getTagUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tagUserId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CancelPKByProto.CancelPKByProtoReq)) {
        return super.equals(obj);
      }
      CancelPKByProto.CancelPKByProtoReq other = (CancelPKByProto.CancelPKByProtoReq) obj;

      boolean result = true;
      result = result && getPkId()
          .equals(other.getPkId());
      result = result && getTagRoomId()
          .equals(other.getTagRoomId());
      result = result && getMyRoomId()
          .equals(other.getMyRoomId());
      result = result && getTagUserId()
          .equals(other.getTagUserId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PKID_FIELD_NUMBER;
      hash = (53 * hash) + getPkId().hashCode();
      hash = (37 * hash) + TAGROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getTagRoomId().hashCode();
      hash = (37 * hash) + MYROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getMyRoomId().hashCode();
      hash = (37 * hash) + TAGUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getTagUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CancelPKByProto.CancelPKByProtoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CancelPKByProtoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CancelPKByProtoReq)
        CancelPKByProto.CancelPKByProtoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CancelPKByProto.CancelPKByProtoReq.class, CancelPKByProto.CancelPKByProtoReq.Builder.class);
      }

      // Construct using CancelPKByProto.CancelPKByProtoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pkId_ = "";

        tagRoomId_ = "";

        myRoomId_ = "";

        tagUserId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoReq_descriptor;
      }

      public CancelPKByProto.CancelPKByProtoReq getDefaultInstanceForType() {
        return CancelPKByProto.CancelPKByProtoReq.getDefaultInstance();
      }

      public CancelPKByProto.CancelPKByProtoReq build() {
        CancelPKByProto.CancelPKByProtoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CancelPKByProto.CancelPKByProtoReq buildPartial() {
        CancelPKByProto.CancelPKByProtoReq result = new CancelPKByProto.CancelPKByProtoReq(this);
        result.pkId_ = pkId_;
        result.tagRoomId_ = tagRoomId_;
        result.myRoomId_ = myRoomId_;
        result.tagUserId_ = tagUserId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CancelPKByProto.CancelPKByProtoReq) {
          return mergeFrom((CancelPKByProto.CancelPKByProtoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CancelPKByProto.CancelPKByProtoReq other) {
        if (other == CancelPKByProto.CancelPKByProtoReq.getDefaultInstance()) return this;
        if (!other.getPkId().isEmpty()) {
          pkId_ = other.pkId_;
          onChanged();
        }
        if (!other.getTagRoomId().isEmpty()) {
          tagRoomId_ = other.tagRoomId_;
          onChanged();
        }
        if (!other.getMyRoomId().isEmpty()) {
          myRoomId_ = other.myRoomId_;
          onChanged();
        }
        if (!other.getTagUserId().isEmpty()) {
          tagUserId_ = other.tagUserId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CancelPKByProto.CancelPKByProtoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CancelPKByProto.CancelPKByProtoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object pkId_ = "";
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public String getPkId() {
        Object ref = pkId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pkId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPkIdBytes() {
        Object ref = pkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder setPkId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder clearPkId() {
        
        pkId_ = getDefaultInstance().getPkId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder setPkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pkId_ = value;
        onChanged();
        return this;
      }

      private Object tagRoomId_ = "";
      /**
       * <pre>
       *对方的房间Id
       * </pre>
       *
       * <code>optional string tagRoomId = 2;</code>
       */
      public String getTagRoomId() {
        Object ref = tagRoomId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagRoomId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *对方的房间Id
       * </pre>
       *
       * <code>optional string tagRoomId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTagRoomIdBytes() {
        Object ref = tagRoomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tagRoomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对方的房间Id
       * </pre>
       *
       * <code>optional string tagRoomId = 2;</code>
       */
      public Builder setTagRoomId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagRoomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方的房间Id
       * </pre>
       *
       * <code>optional string tagRoomId = 2;</code>
       */
      public Builder clearTagRoomId() {
        
        tagRoomId_ = getDefaultInstance().getTagRoomId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方的房间Id
       * </pre>
       *
       * <code>optional string tagRoomId = 2;</code>
       */
      public Builder setTagRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagRoomId_ = value;
        onChanged();
        return this;
      }

      private Object myRoomId_ = "";
      /**
       * <pre>
       *自己的房间Id
       * </pre>
       *
       * <code>optional string myRoomId = 3;</code>
       */
      public String getMyRoomId() {
        Object ref = myRoomId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          myRoomId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *自己的房间Id
       * </pre>
       *
       * <code>optional string myRoomId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMyRoomIdBytes() {
        Object ref = myRoomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          myRoomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *自己的房间Id
       * </pre>
       *
       * <code>optional string myRoomId = 3;</code>
       */
      public Builder setMyRoomId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        myRoomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自己的房间Id
       * </pre>
       *
       * <code>optional string myRoomId = 3;</code>
       */
      public Builder clearMyRoomId() {
        
        myRoomId_ = getDefaultInstance().getMyRoomId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自己的房间Id
       * </pre>
       *
       * <code>optional string myRoomId = 3;</code>
       */
      public Builder setMyRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        myRoomId_ = value;
        onChanged();
        return this;
      }

      private Object tagUserId_ = "";
      /**
       * <pre>
       *对方主播Id
       * </pre>
       *
       * <code>optional string tagUserId = 4;</code>
       */
      public String getTagUserId() {
        Object ref = tagUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *对方主播Id
       * </pre>
       *
       * <code>optional string tagUserId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTagUserIdBytes() {
        Object ref = tagUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tagUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对方主播Id
       * </pre>
       *
       * <code>optional string tagUserId = 4;</code>
       */
      public Builder setTagUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方主播Id
       * </pre>
       *
       * <code>optional string tagUserId = 4;</code>
       */
      public Builder clearTagUserId() {
        
        tagUserId_ = getDefaultInstance().getTagUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方主播Id
       * </pre>
       *
       * <code>optional string tagUserId = 4;</code>
       */
      public Builder setTagUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagUserId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.CancelPKByProtoReq)
    }

    // @@protoc_insertion_point(class_scope:proto.CancelPKByProtoReq)
    private static final CancelPKByProto.CancelPKByProtoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CancelPKByProto.CancelPKByProtoReq();
    }

    public static CancelPKByProto.CancelPKByProtoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CancelPKByProtoReq>
        PARSER = new com.google.protobuf.AbstractParser<CancelPKByProtoReq>() {
      public CancelPKByProtoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CancelPKByProtoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CancelPKByProtoReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CancelPKByProtoReq> getParserForType() {
      return PARSER;
    }

    public CancelPKByProto.CancelPKByProtoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CancelPKByProtoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CancelPKByProtoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsg getMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsgOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code proto.CancelPKByProtoRes}
   */
  public  static final class CancelPKByProtoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CancelPKByProtoRes)
      CancelPKByProtoResOrBuilder {
    // Use CancelPKByProtoRes.newBuilder() to construct.
    private CancelPKByProtoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CancelPKByProtoRes() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CancelPKByProtoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Entity.ReturnMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(Entity.ReturnMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CancelPKByProto.internal_static_proto_CancelPKByProtoRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CancelPKByProto.internal_static_proto_CancelPKByProtoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CancelPKByProto.CancelPKByProtoRes.class, CancelPKByProto.CancelPKByProtoRes.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private Entity.ReturnMsg msg_;
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsg getMsg() {
      return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CancelPKByProto.CancelPKByProtoRes)) {
        return super.equals(obj);
      }
      CancelPKByProto.CancelPKByProtoRes other = (CancelPKByProto.CancelPKByProtoRes) obj;

      boolean result = true;
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CancelPKByProto.CancelPKByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CancelPKByProto.CancelPKByProtoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CancelPKByProtoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CancelPKByProtoRes)
        CancelPKByProto.CancelPKByProtoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CancelPKByProto.CancelPKByProtoRes.class, CancelPKByProto.CancelPKByProtoRes.Builder.class);
      }

      // Construct using CancelPKByProto.CancelPKByProtoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CancelPKByProto.internal_static_proto_CancelPKByProtoRes_descriptor;
      }

      public CancelPKByProto.CancelPKByProtoRes getDefaultInstanceForType() {
        return CancelPKByProto.CancelPKByProtoRes.getDefaultInstance();
      }

      public CancelPKByProto.CancelPKByProtoRes build() {
        CancelPKByProto.CancelPKByProtoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CancelPKByProto.CancelPKByProtoRes buildPartial() {
        CancelPKByProto.CancelPKByProtoRes result = new CancelPKByProto.CancelPKByProtoRes(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CancelPKByProto.CancelPKByProtoRes) {
          return mergeFrom((CancelPKByProto.CancelPKByProtoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CancelPKByProto.CancelPKByProtoRes other) {
        if (other == CancelPKByProto.CancelPKByProtoRes.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CancelPKByProto.CancelPKByProtoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CancelPKByProto.CancelPKByProtoRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Entity.ReturnMsg msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> msgBuilder_;
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(
          Entity.ReturnMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder mergeMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              Entity.ReturnMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              Entity.ReturnMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.CancelPKByProtoRes)
    }

    // @@protoc_insertion_point(class_scope:proto.CancelPKByProtoRes)
    private static final CancelPKByProto.CancelPKByProtoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CancelPKByProto.CancelPKByProtoRes();
    }

    public static CancelPKByProto.CancelPKByProtoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CancelPKByProtoRes>
        PARSER = new com.google.protobuf.AbstractParser<CancelPKByProtoRes>() {
      public CancelPKByProtoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CancelPKByProtoRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CancelPKByProtoRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CancelPKByProtoRes> getParserForType() {
      return PARSER;
    }

    public CancelPKByProto.CancelPKByProtoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CancelPKByProtoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CancelPKByProtoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CancelPKByProtoRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CancelPKByProtoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025CancelPKByProto.proto\022\005proto\032\014Entity.p" +
      "roto\"Z\n\022CancelPKByProtoReq\022\014\n\004pkId\030\001 \001(\t" +
      "\022\021\n\ttagRoomId\030\002 \001(\t\022\020\n\010myRoomId\030\003 \001(\t\022\021\n" +
      "\ttagUserId\030\004 \001(\t\"3\n\022CancelPKByProtoRes\022\035" +
      "\n\003msg\030\001 \001(\0132\020.proto.ReturnMsgB \n\036com.sen" +
      "corsta.ids.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_CancelPKByProtoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CancelPKByProtoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CancelPKByProtoReq_descriptor,
        new String[] { "PkId", "TagRoomId", "MyRoomId", "TagUserId", });
    internal_static_proto_CancelPKByProtoRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CancelPKByProtoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CancelPKByProtoRes_descriptor,
        new String[] { "Msg", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
