// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PKResidueTimeByProto.proto

package com.jk.jkproject.net.im.info;

public final class PKResidueTimeByProto {
  private PKResidueTimeByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PKResidueTimeReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PKResidueTimeReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    String getPkId();
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPkIdBytes();
  }
  /**
   * Protobuf type {@code proto.PKResidueTimeReq}
   */
  public  static final class PKResidueTimeReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PKResidueTimeReq)
      PKResidueTimeReqOrBuilder {
    // Use PKResidueTimeReq.newBuilder() to construct.
    private PKResidueTimeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PKResidueTimeReq() {
      pkId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PKResidueTimeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              pkId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PKResidueTimeByProto.internal_static_proto_PKResidueTimeReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PKResidueTimeByProto.internal_static_proto_PKResidueTimeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PKResidueTimeByProto.PKResidueTimeReq.class, PKResidueTimeByProto.PKResidueTimeReq.Builder.class);
    }

    public static final int PKID_FIELD_NUMBER = 1;
    private volatile Object pkId_;
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    public String getPkId() {
      Object ref = pkId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pkId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *pkid
     * </pre>
     *
     * <code>optional string pkId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPkIdBytes() {
      Object ref = pkId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPkIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pkId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPkIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pkId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PKResidueTimeByProto.PKResidueTimeReq)) {
        return super.equals(obj);
      }
      PKResidueTimeByProto.PKResidueTimeReq other = (PKResidueTimeByProto.PKResidueTimeReq) obj;

      boolean result = true;
      result = result && getPkId()
          .equals(other.getPkId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PKID_FIELD_NUMBER;
      hash = (53 * hash) + getPkId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PKResidueTimeByProto.PKResidueTimeReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PKResidueTimeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PKResidueTimeReq)
        PKResidueTimeByProto.PKResidueTimeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PKResidueTimeByProto.PKResidueTimeReq.class, PKResidueTimeByProto.PKResidueTimeReq.Builder.class);
      }

      // Construct using PKResidueTimeByProto.PKResidueTimeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pkId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeReq_descriptor;
      }

      public PKResidueTimeByProto.PKResidueTimeReq getDefaultInstanceForType() {
        return PKResidueTimeByProto.PKResidueTimeReq.getDefaultInstance();
      }

      public PKResidueTimeByProto.PKResidueTimeReq build() {
        PKResidueTimeByProto.PKResidueTimeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PKResidueTimeByProto.PKResidueTimeReq buildPartial() {
        PKResidueTimeByProto.PKResidueTimeReq result = new PKResidueTimeByProto.PKResidueTimeReq(this);
        result.pkId_ = pkId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PKResidueTimeByProto.PKResidueTimeReq) {
          return mergeFrom((PKResidueTimeByProto.PKResidueTimeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PKResidueTimeByProto.PKResidueTimeReq other) {
        if (other == PKResidueTimeByProto.PKResidueTimeReq.getDefaultInstance()) return this;
        if (!other.getPkId().isEmpty()) {
          pkId_ = other.pkId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PKResidueTimeByProto.PKResidueTimeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PKResidueTimeByProto.PKResidueTimeReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object pkId_ = "";
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public String getPkId() {
        Object ref = pkId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pkId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPkIdBytes() {
        Object ref = pkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder setPkId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder clearPkId() {
        
        pkId_ = getDefaultInstance().getPkId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *pkid
       * </pre>
       *
       * <code>optional string pkId = 1;</code>
       */
      public Builder setPkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pkId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PKResidueTimeReq)
    }

    // @@protoc_insertion_point(class_scope:proto.PKResidueTimeReq)
    private static final PKResidueTimeByProto.PKResidueTimeReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PKResidueTimeByProto.PKResidueTimeReq();
    }

    public static PKResidueTimeByProto.PKResidueTimeReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PKResidueTimeReq>
        PARSER = new com.google.protobuf.AbstractParser<PKResidueTimeReq>() {
      public PKResidueTimeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PKResidueTimeReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PKResidueTimeReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PKResidueTimeReq> getParserForType() {
      return PARSER;
    }

    public PKResidueTimeByProto.PKResidueTimeReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PKResidueTimeResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PKResidueTimeRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsg getMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsgOrBuilder getMsgOrBuilder();

    /**
     * <pre>
     *剩余时间
     * </pre>
     *
     * <code>optional int32 time = 2;</code>
     */
    int getTime();
  }
  /**
   * Protobuf type {@code proto.PKResidueTimeRes}
   */
  public  static final class PKResidueTimeRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PKResidueTimeRes)
      PKResidueTimeResOrBuilder {
    // Use PKResidueTimeRes.newBuilder() to construct.
    private PKResidueTimeRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PKResidueTimeRes() {
      time_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PKResidueTimeRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Entity.ReturnMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(Entity.ReturnMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              time_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PKResidueTimeByProto.internal_static_proto_PKResidueTimeRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PKResidueTimeByProto.internal_static_proto_PKResidueTimeRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PKResidueTimeByProto.PKResidueTimeRes.class, PKResidueTimeByProto.PKResidueTimeRes.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private Entity.ReturnMsg msg_;
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsg getMsg() {
      return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <pre>
     *剩余时间
     * </pre>
     *
     * <code>optional int32 time = 2;</code>
     */
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
      if (time_ != 0) {
        output.writeInt32(2, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      if (time_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PKResidueTimeByProto.PKResidueTimeRes)) {
        return super.equals(obj);
      }
      PKResidueTimeByProto.PKResidueTimeRes other = (PKResidueTimeByProto.PKResidueTimeRes) obj;

      boolean result = true;
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && (getTime()
          == other.getTime());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PKResidueTimeByProto.PKResidueTimeRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PKResidueTimeByProto.PKResidueTimeRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PKResidueTimeRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PKResidueTimeRes)
        PKResidueTimeByProto.PKResidueTimeResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PKResidueTimeByProto.PKResidueTimeRes.class, PKResidueTimeByProto.PKResidueTimeRes.Builder.class);
      }

      // Construct using PKResidueTimeByProto.PKResidueTimeRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        time_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PKResidueTimeByProto.internal_static_proto_PKResidueTimeRes_descriptor;
      }

      public PKResidueTimeByProto.PKResidueTimeRes getDefaultInstanceForType() {
        return PKResidueTimeByProto.PKResidueTimeRes.getDefaultInstance();
      }

      public PKResidueTimeByProto.PKResidueTimeRes build() {
        PKResidueTimeByProto.PKResidueTimeRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PKResidueTimeByProto.PKResidueTimeRes buildPartial() {
        PKResidueTimeByProto.PKResidueTimeRes result = new PKResidueTimeByProto.PKResidueTimeRes(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PKResidueTimeByProto.PKResidueTimeRes) {
          return mergeFrom((PKResidueTimeByProto.PKResidueTimeRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PKResidueTimeByProto.PKResidueTimeRes other) {
        if (other == PKResidueTimeByProto.PKResidueTimeRes.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        if (other.getTime() != 0) {
          setTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PKResidueTimeByProto.PKResidueTimeRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PKResidueTimeByProto.PKResidueTimeRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Entity.ReturnMsg msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> msgBuilder_;
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(
          Entity.ReturnMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder mergeMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              Entity.ReturnMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              Entity.ReturnMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      private int time_ ;
      /**
       * <pre>
       *剩余时间
       * </pre>
       *
       * <code>optional int32 time = 2;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <pre>
       *剩余时间
       * </pre>
       *
       * <code>optional int32 time = 2;</code>
       */
      public Builder setTime(int value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余时间
       * </pre>
       *
       * <code>optional int32 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PKResidueTimeRes)
    }

    // @@protoc_insertion_point(class_scope:proto.PKResidueTimeRes)
    private static final PKResidueTimeByProto.PKResidueTimeRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PKResidueTimeByProto.PKResidueTimeRes();
    }

    public static PKResidueTimeByProto.PKResidueTimeRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PKResidueTimeRes>
        PARSER = new com.google.protobuf.AbstractParser<PKResidueTimeRes>() {
      public PKResidueTimeRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PKResidueTimeRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PKResidueTimeRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PKResidueTimeRes> getParserForType() {
      return PARSER;
    }

    public PKResidueTimeByProto.PKResidueTimeRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PKResidueTimeReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PKResidueTimeReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PKResidueTimeRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PKResidueTimeRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032PKResidueTimeByProto.proto\022\005proto\032\014Ent" +
      "ity.proto\" \n\020PKResidueTimeReq\022\014\n\004pkId\030\001 " +
      "\001(\t\"?\n\020PKResidueTimeRes\022\035\n\003msg\030\001 \001(\0132\020.p" +
      "roto.ReturnMsg\022\014\n\004time\030\002 \001(\005B \n\036com.senc" +
      "orsta.ids.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_PKResidueTimeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PKResidueTimeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PKResidueTimeReq_descriptor,
        new String[] { "PkId", });
    internal_static_proto_PKResidueTimeRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PKResidueTimeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PKResidueTimeRes_descriptor,
        new String[] { "Msg", "Time", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
