// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushPKAnchorInfo.proto

package com.jk.jkproject.net.im.info;

public final class PushPKAnchorInfo {
  private PushPKAnchorInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushPKAnchorInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PushPKAnchorInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *对方的用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    String getUserId();
    /**
     * <pre>
     *对方的用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 2;</code>
     */
    String getNickname();
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 3;</code>
     */
    String getPicture();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 3;</code>
     */
    com.google.protobuf.ByteString
        getPictureBytes();

    /**
     * <pre>
     *主播等级
     * </pre>
     *
     * <code>optional int32 anchorGrade = 4;</code>
     */
    int getAnchorGrade();

    /**
     * <pre>
     *房间Id
     * </pre>
     *
     * <code>optional string roomId = 5;</code>
     */
    String getRoomId();
    /**
     * <pre>
     *房间Id
     * </pre>
     *
     * <code>optional string roomId = 5;</code>
     */
    com.google.protobuf.ByteString
        getRoomIdBytes();

    /**
     * <pre>
     *PK合并的流id
     * </pre>
     *
     * <code>optional string mergeStreamUrl = 6;</code>
     */
    String getMergeStreamUrl();
    /**
     * <pre>
     *PK合并的流id
     * </pre>
     *
     * <code>optional string mergeStreamUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getMergeStreamUrlBytes();

    /**
     * <pre>
     *左边最大胜利数
     * </pre>
     *
     * <code>optional string leftPkMaxVictory = 7;</code>
     */
    String getLeftPkMaxVictory();
    /**
     * <pre>
     *左边最大胜利数
     * </pre>
     *
     * <code>optional string leftPkMaxVictory = 7;</code>
     */
    com.google.protobuf.ByteString
        getLeftPkMaxVictoryBytes();

    /**
     * <pre>
     *右边最大胜利数
     * </pre>
     *
     * <code>optional string rightPkMaxVictory = 8;</code>
     */
    String getRightPkMaxVictory();
    /**
     * <pre>
     *右边最大胜利数
     * </pre>
     *
     * <code>optional string rightPkMaxVictory = 8;</code>
     */
    com.google.protobuf.ByteString
        getRightPkMaxVictoryBytes();
  }
  /**
   * Protobuf type {@code proto.PushPKAnchorInfoMessage}
   */
  public  static final class PushPKAnchorInfoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PushPKAnchorInfoMessage)
      PushPKAnchorInfoMessageOrBuilder {
    // Use PushPKAnchorInfoMessage.newBuilder() to construct.
    private PushPKAnchorInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushPKAnchorInfoMessage() {
      userId_ = "";
      nickname_ = "";
      picture_ = "";
      anchorGrade_ = 0;
      roomId_ = "";
      mergeStreamUrl_ = "";
      leftPkMaxVictory_ = "";
      rightPkMaxVictory_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PushPKAnchorInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              picture_ = s;
              break;
            }
            case 32: {

              anchorGrade_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              roomId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              mergeStreamUrl_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              leftPkMaxVictory_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              rightPkMaxVictory_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PushPKAnchorInfo.internal_static_proto_PushPKAnchorInfoMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PushPKAnchorInfo.internal_static_proto_PushPKAnchorInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PushPKAnchorInfo.PushPKAnchorInfoMessage.class, PushPKAnchorInfo.PushPKAnchorInfoMessage.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <pre>
     *对方的用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对方的用户id
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile Object nickname_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 2;</code>
     */
    public String getNickname() {
      Object ref = nickname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURE_FIELD_NUMBER = 3;
    private volatile Object picture_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 3;</code>
     */
    public String getPicture() {
      Object ref = picture_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        picture_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      Object ref = picture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANCHORGRADE_FIELD_NUMBER = 4;
    private int anchorGrade_;
    /**
     * <pre>
     *主播等级
     * </pre>
     *
     * <code>optional int32 anchorGrade = 4;</code>
     */
    public int getAnchorGrade() {
      return anchorGrade_;
    }

    public static final int ROOMID_FIELD_NUMBER = 5;
    private volatile Object roomId_;
    /**
     * <pre>
     *房间Id
     * </pre>
     *
     * <code>optional string roomId = 5;</code>
     */
    public String getRoomId() {
      Object ref = roomId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *房间Id
     * </pre>
     *
     * <code>optional string roomId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MERGESTREAMURL_FIELD_NUMBER = 6;
    private volatile Object mergeStreamUrl_;
    /**
     * <pre>
     *PK合并的流id
     * </pre>
     *
     * <code>optional string mergeStreamUrl = 6;</code>
     */
    public String getMergeStreamUrl() {
      Object ref = mergeStreamUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mergeStreamUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *PK合并的流id
     * </pre>
     *
     * <code>optional string mergeStreamUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMergeStreamUrlBytes() {
      Object ref = mergeStreamUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mergeStreamUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEFTPKMAXVICTORY_FIELD_NUMBER = 7;
    private volatile Object leftPkMaxVictory_;
    /**
     * <pre>
     *左边最大胜利数
     * </pre>
     *
     * <code>optional string leftPkMaxVictory = 7;</code>
     */
    public String getLeftPkMaxVictory() {
      Object ref = leftPkMaxVictory_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        leftPkMaxVictory_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *左边最大胜利数
     * </pre>
     *
     * <code>optional string leftPkMaxVictory = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLeftPkMaxVictoryBytes() {
      Object ref = leftPkMaxVictory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        leftPkMaxVictory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RIGHTPKMAXVICTORY_FIELD_NUMBER = 8;
    private volatile Object rightPkMaxVictory_;
    /**
     * <pre>
     *右边最大胜利数
     * </pre>
     *
     * <code>optional string rightPkMaxVictory = 8;</code>
     */
    public String getRightPkMaxVictory() {
      Object ref = rightPkMaxVictory_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rightPkMaxVictory_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *右边最大胜利数
     * </pre>
     *
     * <code>optional string rightPkMaxVictory = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRightPkMaxVictoryBytes() {
      Object ref = rightPkMaxVictory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rightPkMaxVictory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_);
      }
      if (!getPictureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, picture_);
      }
      if (anchorGrade_ != 0) {
        output.writeInt32(4, anchorGrade_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roomId_);
      }
      if (!getMergeStreamUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mergeStreamUrl_);
      }
      if (!getLeftPkMaxVictoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, leftPkMaxVictory_);
      }
      if (!getRightPkMaxVictoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, rightPkMaxVictory_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickname_);
      }
      if (!getPictureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, picture_);
      }
      if (anchorGrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, anchorGrade_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roomId_);
      }
      if (!getMergeStreamUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mergeStreamUrl_);
      }
      if (!getLeftPkMaxVictoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, leftPkMaxVictory_);
      }
      if (!getRightPkMaxVictoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, rightPkMaxVictory_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PushPKAnchorInfo.PushPKAnchorInfoMessage)) {
        return super.equals(obj);
      }
      PushPKAnchorInfo.PushPKAnchorInfoMessage other = (PushPKAnchorInfo.PushPKAnchorInfoMessage) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && getPicture()
          .equals(other.getPicture());
      result = result && (getAnchorGrade()
          == other.getAnchorGrade());
      result = result && getRoomId()
          .equals(other.getRoomId());
      result = result && getMergeStreamUrl()
          .equals(other.getMergeStreamUrl());
      result = result && getLeftPkMaxVictory()
          .equals(other.getLeftPkMaxVictory());
      result = result && getRightPkMaxVictory()
          .equals(other.getRightPkMaxVictory());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getPicture().hashCode();
      hash = (37 * hash) + ANCHORGRADE_FIELD_NUMBER;
      hash = (53 * hash) + getAnchorGrade();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
      hash = (37 * hash) + MERGESTREAMURL_FIELD_NUMBER;
      hash = (53 * hash) + getMergeStreamUrl().hashCode();
      hash = (37 * hash) + LEFTPKMAXVICTORY_FIELD_NUMBER;
      hash = (53 * hash) + getLeftPkMaxVictory().hashCode();
      hash = (37 * hash) + RIGHTPKMAXVICTORY_FIELD_NUMBER;
      hash = (53 * hash) + getRightPkMaxVictory().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushPKAnchorInfo.PushPKAnchorInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PushPKAnchorInfo.PushPKAnchorInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PushPKAnchorInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PushPKAnchorInfoMessage)
        PushPKAnchorInfo.PushPKAnchorInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PushPKAnchorInfo.internal_static_proto_PushPKAnchorInfoMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PushPKAnchorInfo.internal_static_proto_PushPKAnchorInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PushPKAnchorInfo.PushPKAnchorInfoMessage.class, PushPKAnchorInfo.PushPKAnchorInfoMessage.Builder.class);
      }

      // Construct using PushPKAnchorInfo.PushPKAnchorInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        nickname_ = "";

        picture_ = "";

        anchorGrade_ = 0;

        roomId_ = "";

        mergeStreamUrl_ = "";

        leftPkMaxVictory_ = "";

        rightPkMaxVictory_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PushPKAnchorInfo.internal_static_proto_PushPKAnchorInfoMessage_descriptor;
      }

      public PushPKAnchorInfo.PushPKAnchorInfoMessage getDefaultInstanceForType() {
        return PushPKAnchorInfo.PushPKAnchorInfoMessage.getDefaultInstance();
      }

      public PushPKAnchorInfo.PushPKAnchorInfoMessage build() {
        PushPKAnchorInfo.PushPKAnchorInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PushPKAnchorInfo.PushPKAnchorInfoMessage buildPartial() {
        PushPKAnchorInfo.PushPKAnchorInfoMessage result = new PushPKAnchorInfo.PushPKAnchorInfoMessage(this);
        result.userId_ = userId_;
        result.nickname_ = nickname_;
        result.picture_ = picture_;
        result.anchorGrade_ = anchorGrade_;
        result.roomId_ = roomId_;
        result.mergeStreamUrl_ = mergeStreamUrl_;
        result.leftPkMaxVictory_ = leftPkMaxVictory_;
        result.rightPkMaxVictory_ = rightPkMaxVictory_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PushPKAnchorInfo.PushPKAnchorInfoMessage) {
          return mergeFrom((PushPKAnchorInfo.PushPKAnchorInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PushPKAnchorInfo.PushPKAnchorInfoMessage other) {
        if (other == PushPKAnchorInfo.PushPKAnchorInfoMessage.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getPicture().isEmpty()) {
          picture_ = other.picture_;
          onChanged();
        }
        if (other.getAnchorGrade() != 0) {
          setAnchorGrade(other.getAnchorGrade());
        }
        if (!other.getRoomId().isEmpty()) {
          roomId_ = other.roomId_;
          onChanged();
        }
        if (!other.getMergeStreamUrl().isEmpty()) {
          mergeStreamUrl_ = other.mergeStreamUrl_;
          onChanged();
        }
        if (!other.getLeftPkMaxVictory().isEmpty()) {
          leftPkMaxVictory_ = other.leftPkMaxVictory_;
          onChanged();
        }
        if (!other.getRightPkMaxVictory().isEmpty()) {
          rightPkMaxVictory_ = other.rightPkMaxVictory_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PushPKAnchorInfo.PushPKAnchorInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PushPKAnchorInfo.PushPKAnchorInfoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *对方的用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *对方的用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对方的用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方的用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方的用户id
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object nickname_ = "";
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 2;</code>
       */
      public String getNickname() {
        Object ref = nickname_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNickname(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 2;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private Object picture_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 3;</code>
       */
      public String getPicture() {
        Object ref = picture_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          picture_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPictureBytes() {
        Object ref = picture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          picture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 3;</code>
       */
      public Builder setPicture(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        picture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 3;</code>
       */
      public Builder clearPicture() {
        
        picture_ = getDefaultInstance().getPicture();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 3;</code>
       */
      public Builder setPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        picture_ = value;
        onChanged();
        return this;
      }

      private int anchorGrade_ ;
      /**
       * <pre>
       *主播等级
       * </pre>
       *
       * <code>optional int32 anchorGrade = 4;</code>
       */
      public int getAnchorGrade() {
        return anchorGrade_;
      }
      /**
       * <pre>
       *主播等级
       * </pre>
       *
       * <code>optional int32 anchorGrade = 4;</code>
       */
      public Builder setAnchorGrade(int value) {
        
        anchorGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主播等级
       * </pre>
       *
       * <code>optional int32 anchorGrade = 4;</code>
       */
      public Builder clearAnchorGrade() {
        
        anchorGrade_ = 0;
        onChanged();
        return this;
      }

      private Object roomId_ = "";
      /**
       * <pre>
       *房间Id
       * </pre>
       *
       * <code>optional string roomId = 5;</code>
       */
      public String getRoomId() {
        Object ref = roomId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roomId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *房间Id
       * </pre>
       *
       * <code>optional string roomId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes() {
        Object ref = roomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *房间Id
       * </pre>
       *
       * <code>optional string roomId = 5;</code>
       */
      public Builder setRoomId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间Id
       * </pre>
       *
       * <code>optional string roomId = 5;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = getDefaultInstance().getRoomId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间Id
       * </pre>
       *
       * <code>optional string roomId = 5;</code>
       */
      public Builder setRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomId_ = value;
        onChanged();
        return this;
      }

      private Object mergeStreamUrl_ = "";
      /**
       * <pre>
       *PK合并的流id
       * </pre>
       *
       * <code>optional string mergeStreamUrl = 6;</code>
       */
      public String getMergeStreamUrl() {
        Object ref = mergeStreamUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mergeStreamUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *PK合并的流id
       * </pre>
       *
       * <code>optional string mergeStreamUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMergeStreamUrlBytes() {
        Object ref = mergeStreamUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mergeStreamUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *PK合并的流id
       * </pre>
       *
       * <code>optional string mergeStreamUrl = 6;</code>
       */
      public Builder setMergeStreamUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mergeStreamUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *PK合并的流id
       * </pre>
       *
       * <code>optional string mergeStreamUrl = 6;</code>
       */
      public Builder clearMergeStreamUrl() {
        
        mergeStreamUrl_ = getDefaultInstance().getMergeStreamUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *PK合并的流id
       * </pre>
       *
       * <code>optional string mergeStreamUrl = 6;</code>
       */
      public Builder setMergeStreamUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mergeStreamUrl_ = value;
        onChanged();
        return this;
      }

      private Object leftPkMaxVictory_ = "";
      /**
       * <pre>
       *左边最大胜利数
       * </pre>
       *
       * <code>optional string leftPkMaxVictory = 7;</code>
       */
      public String getLeftPkMaxVictory() {
        Object ref = leftPkMaxVictory_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          leftPkMaxVictory_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *左边最大胜利数
       * </pre>
       *
       * <code>optional string leftPkMaxVictory = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLeftPkMaxVictoryBytes() {
        Object ref = leftPkMaxVictory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          leftPkMaxVictory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *左边最大胜利数
       * </pre>
       *
       * <code>optional string leftPkMaxVictory = 7;</code>
       */
      public Builder setLeftPkMaxVictory(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leftPkMaxVictory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *左边最大胜利数
       * </pre>
       *
       * <code>optional string leftPkMaxVictory = 7;</code>
       */
      public Builder clearLeftPkMaxVictory() {
        
        leftPkMaxVictory_ = getDefaultInstance().getLeftPkMaxVictory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *左边最大胜利数
       * </pre>
       *
       * <code>optional string leftPkMaxVictory = 7;</code>
       */
      public Builder setLeftPkMaxVictoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leftPkMaxVictory_ = value;
        onChanged();
        return this;
      }

      private Object rightPkMaxVictory_ = "";
      /**
       * <pre>
       *右边最大胜利数
       * </pre>
       *
       * <code>optional string rightPkMaxVictory = 8;</code>
       */
      public String getRightPkMaxVictory() {
        Object ref = rightPkMaxVictory_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rightPkMaxVictory_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *右边最大胜利数
       * </pre>
       *
       * <code>optional string rightPkMaxVictory = 8;</code>
       */
      public com.google.protobuf.ByteString
          getRightPkMaxVictoryBytes() {
        Object ref = rightPkMaxVictory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rightPkMaxVictory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *右边最大胜利数
       * </pre>
       *
       * <code>optional string rightPkMaxVictory = 8;</code>
       */
      public Builder setRightPkMaxVictory(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rightPkMaxVictory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *右边最大胜利数
       * </pre>
       *
       * <code>optional string rightPkMaxVictory = 8;</code>
       */
      public Builder clearRightPkMaxVictory() {
        
        rightPkMaxVictory_ = getDefaultInstance().getRightPkMaxVictory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *右边最大胜利数
       * </pre>
       *
       * <code>optional string rightPkMaxVictory = 8;</code>
       */
      public Builder setRightPkMaxVictoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rightPkMaxVictory_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PushPKAnchorInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.PushPKAnchorInfoMessage)
    private static final PushPKAnchorInfo.PushPKAnchorInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushPKAnchorInfo.PushPKAnchorInfoMessage();
    }

    public static PushPKAnchorInfo.PushPKAnchorInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushPKAnchorInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<PushPKAnchorInfoMessage>() {
      public PushPKAnchorInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushPKAnchorInfoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushPKAnchorInfoMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PushPKAnchorInfoMessage> getParserForType() {
      return PARSER;
    }

    public PushPKAnchorInfo.PushPKAnchorInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PushPKAnchorInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PushPKAnchorInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026PushPKAnchorInfo.proto\022\005proto\032\014Entity." +
      "proto\"\276\001\n\027PushPKAnchorInfoMessage\022\016\n\006use" +
      "rId\030\001 \001(\t\022\020\n\010nickname\030\002 \001(\t\022\017\n\007picture\030\003" +
      " \001(\t\022\023\n\013anchorGrade\030\004 \001(\005\022\016\n\006roomId\030\005 \001(" +
      "\t\022\026\n\016mergeStreamUrl\030\006 \001(\t\022\030\n\020leftPkMaxVi" +
      "ctory\030\007 \001(\t\022\031\n\021rightPkMaxVictory\030\010 \001(\tB " +
      "\n\036com.sencorsta.ids.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_PushPKAnchorInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PushPKAnchorInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PushPKAnchorInfoMessage_descriptor,
        new String[] { "UserId", "Nickname", "Picture", "AnchorGrade", "RoomId", "MergeStreamUrl", "LeftPkMaxVictory", "RightPkMaxVictory", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
