// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushGiftByProto.proto

package com.jk.jkproject.net.im.info;

public final class PushGiftByProto {
  private PushGiftByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pushGiftOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.pushGift)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0.没有svga 1:有svga
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     * 0.单送礼物 1:连送礼物
     * </pre>
     *
     * <code>optional int32 status = 2;</code>
     */
    int getStatus();

    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 3;</code>
     */
    String getUserId();
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 4;</code>
     */
    String getPicture();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 4;</code>
     */
    com.google.protobuf.ByteString
        getPictureBytes();

    /**
     * <pre>
     *发送方userName
     * </pre>
     *
     * <code>optional string username = 5;</code>
     */
    String getUsername();
    /**
     * <pre>
     *发送方userName
     * </pre>
     *
     * <code>optional string username = 5;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     *礼物Id
     * </pre>
     *
     * <code>optional string giftId = 6;</code>
     */
    String getGiftId();
    /**
     * <pre>
     *礼物Id
     * </pre>
     *
     * <code>optional string giftId = 6;</code>
     */
    com.google.protobuf.ByteString
        getGiftIdBytes();

    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>optional string giftName = 7;</code>
     */
    String getGiftName();
    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>optional string giftName = 7;</code>
     */
    com.google.protobuf.ByteString
        getGiftNameBytes();

    /**
     * <pre>
     *礼物链接
     * </pre>
     *
     * <code>optional string giftUrl = 8;</code>
     */
    String getGiftUrl();
    /**
     * <pre>
     *礼物链接
     * </pre>
     *
     * <code>optional string giftUrl = 8;</code>
     */
    com.google.protobuf.ByteString
        getGiftUrlBytes();

    /**
     * <pre>
     *svga礼物链接
     * </pre>
     *
     * <code>optional string gCartoonUrl = 9;</code>
     */
    String getGCartoonUrl();
    /**
     * <pre>
     *svga礼物链接
     * </pre>
     *
     * <code>optional string gCartoonUrl = 9;</code>
     */
    com.google.protobuf.ByteString
        getGCartoonUrlBytes();

    /**
     * <pre>
     *礼物数量
     * </pre>
     *
     * <code>optional int32 amount = 10;</code>
     */
    int getAmount();

    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional string msgId = 11;</code>
     */
    String getMsgId();
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional string msgId = 11;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();
  }
  /**
   * Protobuf type {@code proto.pushGift}
   */
  public  static final class pushGift extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.pushGift)
      pushGiftOrBuilder {
    // Use pushGift.newBuilder() to construct.
    private pushGift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pushGift() {
      type_ = 0;
      status_ = 0;
      userId_ = "";
      picture_ = "";
      username_ = "";
      giftId_ = "";
      giftName_ = "";
      giftUrl_ = "";
      gCartoonUrl_ = "";
      amount_ = 0;
      msgId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private pushGift(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              picture_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              giftId_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              giftName_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              giftUrl_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              gCartoonUrl_ = s;
              break;
            }
            case 80: {

              amount_ = input.readInt32();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PushGiftByProto.internal_static_proto_pushGift_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PushGiftByProto.internal_static_proto_pushGift_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PushGiftByProto.pushGift.class, PushGiftByProto.pushGift.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 0.没有svga 1:有svga
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <pre>
     * 0.单送礼物 1:连送礼物
     * </pre>
     *
     * <code>optional int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile Object userId_;
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 3;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURE_FIELD_NUMBER = 4;
    private volatile Object picture_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 4;</code>
     */
    public String getPicture() {
      Object ref = picture_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        picture_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      Object ref = picture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private volatile Object username_;
    /**
     * <pre>
     *发送方userName
     * </pre>
     *
     * <code>optional string username = 5;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方userName
     * </pre>
     *
     * <code>optional string username = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIFTID_FIELD_NUMBER = 6;
    private volatile Object giftId_;
    /**
     * <pre>
     *礼物Id
     * </pre>
     *
     * <code>optional string giftId = 6;</code>
     */
    public String getGiftId() {
      Object ref = giftId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        giftId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *礼物Id
     * </pre>
     *
     * <code>optional string giftId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGiftIdBytes() {
      Object ref = giftId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        giftId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIFTNAME_FIELD_NUMBER = 7;
    private volatile Object giftName_;
    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>optional string giftName = 7;</code>
     */
    public String getGiftName() {
      Object ref = giftName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        giftName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *礼物名称
     * </pre>
     *
     * <code>optional string giftName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGiftNameBytes() {
      Object ref = giftName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        giftName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIFTURL_FIELD_NUMBER = 8;
    private volatile Object giftUrl_;
    /**
     * <pre>
     *礼物链接
     * </pre>
     *
     * <code>optional string giftUrl = 8;</code>
     */
    public String getGiftUrl() {
      Object ref = giftUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        giftUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *礼物链接
     * </pre>
     *
     * <code>optional string giftUrl = 8;</code>
     */
    public com.google.protobuf.ByteString
        getGiftUrlBytes() {
      Object ref = giftUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        giftUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GCARTOONURL_FIELD_NUMBER = 9;
    private volatile Object gCartoonUrl_;
    /**
     * <pre>
     *svga礼物链接
     * </pre>
     *
     * <code>optional string gCartoonUrl = 9;</code>
     */
    public String getGCartoonUrl() {
      Object ref = gCartoonUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gCartoonUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *svga礼物链接
     * </pre>
     *
     * <code>optional string gCartoonUrl = 9;</code>
     */
    public com.google.protobuf.ByteString
        getGCartoonUrlBytes() {
      Object ref = gCartoonUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gCartoonUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 10;
    private int amount_;
    /**
     * <pre>
     *礼物数量
     * </pre>
     *
     * <code>optional int32 amount = 10;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int MSGID_FIELD_NUMBER = 11;
    private volatile Object msgId_;
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional string msgId = 11;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional string msgId = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
      }
      if (!getPictureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, picture_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, username_);
      }
      if (!getGiftIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, giftId_);
      }
      if (!getGiftNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, giftName_);
      }
      if (!getGiftUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, giftUrl_);
      }
      if (!getGCartoonUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, gCartoonUrl_);
      }
      if (amount_ != 0) {
        output.writeInt32(10, amount_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, msgId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
      }
      if (!getPictureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, picture_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, username_);
      }
      if (!getGiftIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, giftId_);
      }
      if (!getGiftNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, giftName_);
      }
      if (!getGiftUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, giftUrl_);
      }
      if (!getGCartoonUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, gCartoonUrl_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, amount_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, msgId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PushGiftByProto.pushGift)) {
        return super.equals(obj);
      }
      PushGiftByProto.pushGift other = (PushGiftByProto.pushGift) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getPicture()
          .equals(other.getPicture());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getGiftId()
          .equals(other.getGiftId());
      result = result && getGiftName()
          .equals(other.getGiftName());
      result = result && getGiftUrl()
          .equals(other.getGiftUrl());
      result = result && getGCartoonUrl()
          .equals(other.getGCartoonUrl());
      result = result && (getAmount()
          == other.getAmount());
      result = result && getMsgId()
          .equals(other.getMsgId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getPicture().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + GIFTID_FIELD_NUMBER;
      hash = (53 * hash) + getGiftId().hashCode();
      hash = (37 * hash) + GIFTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGiftName().hashCode();
      hash = (37 * hash) + GIFTURL_FIELD_NUMBER;
      hash = (53 * hash) + getGiftUrl().hashCode();
      hash = (37 * hash) + GCARTOONURL_FIELD_NUMBER;
      hash = (53 * hash) + getGCartoonUrl().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PushGiftByProto.pushGift parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushGiftByProto.pushGift parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushGiftByProto.pushGift parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushGiftByProto.pushGift parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushGiftByProto.pushGift parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushGiftByProto.pushGift parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushGiftByProto.pushGift parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PushGiftByProto.pushGift parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushGiftByProto.pushGift parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushGiftByProto.pushGift parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PushGiftByProto.pushGift prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.pushGift}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.pushGift)
        PushGiftByProto.pushGiftOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PushGiftByProto.internal_static_proto_pushGift_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PushGiftByProto.internal_static_proto_pushGift_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PushGiftByProto.pushGift.class, PushGiftByProto.pushGift.Builder.class);
      }

      // Construct using com.sencorsta.ids.common.proto.PushGiftByProto.pushGift.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        status_ = 0;

        userId_ = "";

        picture_ = "";

        username_ = "";

        giftId_ = "";

        giftName_ = "";

        giftUrl_ = "";

        gCartoonUrl_ = "";

        amount_ = 0;

        msgId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PushGiftByProto.internal_static_proto_pushGift_descriptor;
      }

      public PushGiftByProto.pushGift getDefaultInstanceForType() {
        return PushGiftByProto.pushGift.getDefaultInstance();
      }

      public PushGiftByProto.pushGift build() {
        PushGiftByProto.pushGift result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PushGiftByProto.pushGift buildPartial() {
        PushGiftByProto.pushGift result = new PushGiftByProto.pushGift(this);
        result.type_ = type_;
        result.status_ = status_;
        result.userId_ = userId_;
        result.picture_ = picture_;
        result.username_ = username_;
        result.giftId_ = giftId_;
        result.giftName_ = giftName_;
        result.giftUrl_ = giftUrl_;
        result.gCartoonUrl_ = gCartoonUrl_;
        result.amount_ = amount_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PushGiftByProto.pushGift) {
          return mergeFrom((PushGiftByProto.pushGift)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PushGiftByProto.pushGift other) {
        if (other == PushGiftByProto.pushGift.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getPicture().isEmpty()) {
          picture_ = other.picture_;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getGiftId().isEmpty()) {
          giftId_ = other.giftId_;
          onChanged();
        }
        if (!other.getGiftName().isEmpty()) {
          giftName_ = other.giftName_;
          onChanged();
        }
        if (!other.getGiftUrl().isEmpty()) {
          giftUrl_ = other.giftUrl_;
          onChanged();
        }
        if (!other.getGCartoonUrl().isEmpty()) {
          gCartoonUrl_ = other.gCartoonUrl_;
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PushGiftByProto.pushGift parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PushGiftByProto.pushGift) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 0.没有svga 1:有svga
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 0.没有svga 1:有svga
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0.没有svga 1:有svga
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 0.单送礼物 1:连送礼物
       * </pre>
       *
       * <code>optional int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 0.单送礼物 1:连送礼物
       * </pre>
       *
       * <code>optional int32 status = 2;</code>
       */
      public Builder setStatus(int value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0.单送礼物 1:连送礼物
       * </pre>
       *
       * <code>optional int32 status = 2;</code>
       */
      public Builder clearStatus() {

        status_ = 0;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 3;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 3;</code>
       */
      public Builder clearUserId() {

        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        userId_ = value;
        onChanged();
        return this;
      }

      private Object picture_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 4;</code>
       */
      public String getPicture() {
        Object ref = picture_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          picture_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPictureBytes() {
        Object ref = picture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          picture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 4;</code>
       */
      public Builder setPicture(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        picture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 4;</code>
       */
      public Builder clearPicture() {

        picture_ = getDefaultInstance().getPicture();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 4;</code>
       */
      public Builder setPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        picture_ = value;
        onChanged();
        return this;
      }

      private Object username_ = "";
      /**
       * <pre>
       *发送方userName
       * </pre>
       *
       * <code>optional string username = 5;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送方userName
       * </pre>
       *
       * <code>optional string username = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方userName
       * </pre>
       *
       * <code>optional string username = 5;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userName
       * </pre>
       *
       * <code>optional string username = 5;</code>
       */
      public Builder clearUsername() {

        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userName
       * </pre>
       *
       * <code>optional string username = 5;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        username_ = value;
        onChanged();
        return this;
      }

      private Object giftId_ = "";
      /**
       * <pre>
       *礼物Id
       * </pre>
       *
       * <code>optional string giftId = 6;</code>
       */
      public String getGiftId() {
        Object ref = giftId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          giftId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *礼物Id
       * </pre>
       *
       * <code>optional string giftId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGiftIdBytes() {
        Object ref = giftId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          giftId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *礼物Id
       * </pre>
       *
       * <code>optional string giftId = 6;</code>
       */
      public Builder setGiftId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        giftId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物Id
       * </pre>
       *
       * <code>optional string giftId = 6;</code>
       */
      public Builder clearGiftId() {

        giftId_ = getDefaultInstance().getGiftId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物Id
       * </pre>
       *
       * <code>optional string giftId = 6;</code>
       */
      public Builder setGiftIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        giftId_ = value;
        onChanged();
        return this;
      }

      private Object giftName_ = "";
      /**
       * <pre>
       *礼物名称
       * </pre>
       *
       * <code>optional string giftName = 7;</code>
       */
      public String getGiftName() {
        Object ref = giftName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          giftName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *礼物名称
       * </pre>
       *
       * <code>optional string giftName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGiftNameBytes() {
        Object ref = giftName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          giftName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *礼物名称
       * </pre>
       *
       * <code>optional string giftName = 7;</code>
       */
      public Builder setGiftName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        giftName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物名称
       * </pre>
       *
       * <code>optional string giftName = 7;</code>
       */
      public Builder clearGiftName() {

        giftName_ = getDefaultInstance().getGiftName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物名称
       * </pre>
       *
       * <code>optional string giftName = 7;</code>
       */
      public Builder setGiftNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        giftName_ = value;
        onChanged();
        return this;
      }

      private Object giftUrl_ = "";
      /**
       * <pre>
       *礼物链接
       * </pre>
       *
       * <code>optional string giftUrl = 8;</code>
       */
      public String getGiftUrl() {
        Object ref = giftUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          giftUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *礼物链接
       * </pre>
       *
       * <code>optional string giftUrl = 8;</code>
       */
      public com.google.protobuf.ByteString
          getGiftUrlBytes() {
        Object ref = giftUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          giftUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *礼物链接
       * </pre>
       *
       * <code>optional string giftUrl = 8;</code>
       */
      public Builder setGiftUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        giftUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物链接
       * </pre>
       *
       * <code>optional string giftUrl = 8;</code>
       */
      public Builder clearGiftUrl() {

        giftUrl_ = getDefaultInstance().getGiftUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物链接
       * </pre>
       *
       * <code>optional string giftUrl = 8;</code>
       */
      public Builder setGiftUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        giftUrl_ = value;
        onChanged();
        return this;
      }

      private Object gCartoonUrl_ = "";
      /**
       * <pre>
       *svga礼物链接
       * </pre>
       *
       * <code>optional string gCartoonUrl = 9;</code>
       */
      public String getGCartoonUrl() {
        Object ref = gCartoonUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gCartoonUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *svga礼物链接
       * </pre>
       *
       * <code>optional string gCartoonUrl = 9;</code>
       */
      public com.google.protobuf.ByteString
          getGCartoonUrlBytes() {
        Object ref = gCartoonUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gCartoonUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *svga礼物链接
       * </pre>
       *
       * <code>optional string gCartoonUrl = 9;</code>
       */
      public Builder setGCartoonUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        gCartoonUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *svga礼物链接
       * </pre>
       *
       * <code>optional string gCartoonUrl = 9;</code>
       */
      public Builder clearGCartoonUrl() {

        gCartoonUrl_ = getDefaultInstance().getGCartoonUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *svga礼物链接
       * </pre>
       *
       * <code>optional string gCartoonUrl = 9;</code>
       */
      public Builder setGCartoonUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        gCartoonUrl_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <pre>
       *礼物数量
       * </pre>
       *
       * <code>optional int32 amount = 10;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <pre>
       *礼物数量
       * </pre>
       *
       * <code>optional int32 amount = 10;</code>
       */
      public Builder setAmount(int value) {

        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *礼物数量
       * </pre>
       *
       * <code>optional int32 amount = 10;</code>
       */
      public Builder clearAmount() {

        amount_ = 0;
        onChanged();
        return this;
      }

      private Object msgId_ = "";
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional string msgId = 11;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional string msgId = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional string msgId = 11;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional string msgId = 11;</code>
       */
      public Builder clearMsgId() {

        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional string msgId = 11;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msgId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.pushGift)
    }

    // @@protoc_insertion_point(class_scope:proto.pushGift)
    private static final PushGiftByProto.pushGift DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushGiftByProto.pushGift();
    }

    public static PushGiftByProto.pushGift getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pushGift>
        PARSER = new com.google.protobuf.AbstractParser<pushGift>() {
      public pushGift parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new pushGift(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pushGift> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<pushGift> getParserForType() {
      return PARSER;
    }

    public PushGiftByProto.pushGift getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_pushGift_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_pushGift_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025PushGiftByProto.proto\022\005proto\032\014Entity.p" +
      "roto\"\302\001\n\010pushGift\022\014\n\004type\030\001 \001(\005\022\016\n\006statu" +
      "s\030\002 \001(\005\022\016\n\006userId\030\003 \001(\t\022\017\n\007picture\030\004 \001(\t" +
      "\022\020\n\010username\030\005 \001(\t\022\016\n\006giftId\030\006 \001(\t\022\020\n\010gi" +
      "ftName\030\007 \001(\t\022\017\n\007giftUrl\030\010 \001(\t\022\023\n\013gCartoo" +
      "nUrl\030\t \001(\t\022\016\n\006amount\030\n \001(\005\022\r\n\005msgId\030\013 \001(" +
      "\tB \n\036com.sencorsta.ids.common.protob\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_pushGift_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_pushGift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_pushGift_descriptor,
        new String[] { "Type", "Status", "UserId", "Picture", "Username", "GiftId", "GiftName", "GiftUrl", "GCartoonUrl", "Amount", "MsgId", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
