// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushLinkByProto.proto

package com.jk.jkproject.net.im.info;

public final class PushLinkByProto {
  private PushLinkByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pushLonkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.pushLonk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    String getUserId();
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 2;</code>
     */
    String getPicture();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 2;</code>
     */
    com.google.protobuf.ByteString
        getPictureBytes();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 3;</code>
     */
    String getNickname();
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 3;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *用户等级
     * </pre>
     *
     * <code>optional int32 userGrade = 4;</code>
     */
    int getUserGrade();

    /**
     * <pre>
     *剩余时长
     * </pre>
     *
     * <code>optional int32 time = 5;</code>
     */
    int getTime();

    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 6;</code>
     */
    String getStreamId();
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 6;</code>
     */
    com.google.protobuf.ByteString
        getStreamIdBytes();
  }
  /**
   * Protobuf type {@code proto.pushLonk}
   */
  public  static final class pushLonk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.pushLonk)
      pushLonkOrBuilder {
    // Use pushLonk.newBuilder() to construct.
    private pushLonk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pushLonk() {
      userId_ = "";
      picture_ = "";
      nickname_ = "";
      userGrade_ = 0;
      time_ = 0;
      streamId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private pushLonk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              picture_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 32: {

              userGrade_ = input.readInt32();
              break;
            }
            case 40: {

              time_ = input.readInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              streamId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PushLinkByProto.internal_static_proto_pushLonk_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PushLinkByProto.internal_static_proto_pushLonk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PushLinkByProto.pushLonk.class, PushLinkByProto.pushLonk.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方userId
     * </pre>
     *
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURE_FIELD_NUMBER = 2;
    private volatile Object picture_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 2;</code>
     */
    public String getPicture() {
      Object ref = picture_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        picture_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>optional string picture = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      Object ref = picture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile Object nickname_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 3;</code>
     */
    public String getNickname() {
      Object ref = nickname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>optional string nickname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERGRADE_FIELD_NUMBER = 4;
    private int userGrade_;
    /**
     * <pre>
     *用户等级
     * </pre>
     *
     * <code>optional int32 userGrade = 4;</code>
     */
    public int getUserGrade() {
      return userGrade_;
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private int time_;
    /**
     * <pre>
     *剩余时长
     * </pre>
     *
     * <code>optional int32 time = 5;</code>
     */
    public int getTime() {
      return time_;
    }

    public static final int STREAMID_FIELD_NUMBER = 6;
    private volatile Object streamId_;
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 6;</code>
     */
    public String getStreamId() {
      Object ref = streamId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        streamId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *申请方连麦的流id
     * </pre>
     *
     * <code>optional string streamId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStreamIdBytes() {
      Object ref = streamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        streamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getPictureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, picture_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
      }
      if (userGrade_ != 0) {
        output.writeInt32(4, userGrade_);
      }
      if (time_ != 0) {
        output.writeInt32(5, time_);
      }
      if (!getStreamIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, streamId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getPictureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, picture_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
      }
      if (userGrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userGrade_);
      }
      if (time_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, time_);
      }
      if (!getStreamIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, streamId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PushLinkByProto.pushLonk)) {
        return super.equals(obj);
      }
      PushLinkByProto.pushLonk other = (PushLinkByProto.pushLonk) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getPicture()
          .equals(other.getPicture());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && (getUserGrade()
          == other.getUserGrade());
      result = result && (getTime()
          == other.getTime());
      result = result && getStreamId()
          .equals(other.getStreamId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getPicture().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + USERGRADE_FIELD_NUMBER;
      hash = (53 * hash) + getUserGrade();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime();
      hash = (37 * hash) + STREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getStreamId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PushLinkByProto.pushLonk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushLinkByProto.pushLonk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushLinkByProto.pushLonk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushLinkByProto.pushLonk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushLinkByProto.pushLonk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushLinkByProto.pushLonk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushLinkByProto.pushLonk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PushLinkByProto.pushLonk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushLinkByProto.pushLonk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushLinkByProto.pushLonk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PushLinkByProto.pushLonk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.pushLonk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.pushLonk)
        PushLinkByProto.pushLonkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PushLinkByProto.internal_static_proto_pushLonk_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PushLinkByProto.internal_static_proto_pushLonk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PushLinkByProto.pushLonk.class, PushLinkByProto.pushLonk.Builder.class);
      }

      // Construct using PushLinkByProto.pushLonk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        picture_ = "";

        nickname_ = "";

        userGrade_ = 0;

        time_ = 0;

        streamId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PushLinkByProto.internal_static_proto_pushLonk_descriptor;
      }

      public PushLinkByProto.pushLonk getDefaultInstanceForType() {
        return PushLinkByProto.pushLonk.getDefaultInstance();
      }

      public PushLinkByProto.pushLonk build() {
        PushLinkByProto.pushLonk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PushLinkByProto.pushLonk buildPartial() {
        PushLinkByProto.pushLonk result = new PushLinkByProto.pushLonk(this);
        result.userId_ = userId_;
        result.picture_ = picture_;
        result.nickname_ = nickname_;
        result.userGrade_ = userGrade_;
        result.time_ = time_;
        result.streamId_ = streamId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PushLinkByProto.pushLonk) {
          return mergeFrom((PushLinkByProto.pushLonk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PushLinkByProto.pushLonk other) {
        if (other == PushLinkByProto.pushLonk.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getPicture().isEmpty()) {
          picture_ = other.picture_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.getUserGrade() != 0) {
          setUserGrade(other.getUserGrade());
        }
        if (other.getTime() != 0) {
          setTime(other.getTime());
        }
        if (!other.getStreamId().isEmpty()) {
          streamId_ = other.streamId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PushLinkByProto.pushLonk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PushLinkByProto.pushLonk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方userId
       * </pre>
       *
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object picture_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 2;</code>
       */
      public String getPicture() {
        Object ref = picture_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          picture_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPictureBytes() {
        Object ref = picture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          picture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 2;</code>
       */
      public Builder setPicture(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        picture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 2;</code>
       */
      public Builder clearPicture() {
        
        picture_ = getDefaultInstance().getPicture();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>optional string picture = 2;</code>
       */
      public Builder setPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        picture_ = value;
        onChanged();
        return this;
      }

      private Object nickname_ = "";
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 3;</code>
       */
      public String getNickname() {
        Object ref = nickname_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNickname(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 3;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private int userGrade_ ;
      /**
       * <pre>
       *用户等级
       * </pre>
       *
       * <code>optional int32 userGrade = 4;</code>
       */
      public int getUserGrade() {
        return userGrade_;
      }
      /**
       * <pre>
       *用户等级
       * </pre>
       *
       * <code>optional int32 userGrade = 4;</code>
       */
      public Builder setUserGrade(int value) {
        
        userGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户等级
       * </pre>
       *
       * <code>optional int32 userGrade = 4;</code>
       */
      public Builder clearUserGrade() {
        
        userGrade_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <pre>
       *剩余时长
       * </pre>
       *
       * <code>optional int32 time = 5;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <pre>
       *剩余时长
       * </pre>
       *
       * <code>optional int32 time = 5;</code>
       */
      public Builder setTime(int value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余时长
       * </pre>
       *
       * <code>optional int32 time = 5;</code>
       */
      public Builder clearTime() {
        
        time_ = 0;
        onChanged();
        return this;
      }

      private Object streamId_ = "";
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 6;</code>
       */
      public String getStreamId() {
        Object ref = streamId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          streamId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStreamIdBytes() {
        Object ref = streamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          streamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 6;</code>
       */
      public Builder setStreamId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 6;</code>
       */
      public Builder clearStreamId() {
        
        streamId_ = getDefaultInstance().getStreamId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *申请方连麦的流id
       * </pre>
       *
       * <code>optional string streamId = 6;</code>
       */
      public Builder setStreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streamId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.pushLonk)
    }

    // @@protoc_insertion_point(class_scope:proto.pushLonk)
    private static final PushLinkByProto.pushLonk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushLinkByProto.pushLonk();
    }

    public static PushLinkByProto.pushLonk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pushLonk>
        PARSER = new com.google.protobuf.AbstractParser<pushLonk>() {
      public pushLonk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new pushLonk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pushLonk> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<pushLonk> getParserForType() {
      return PARSER;
    }

    public PushLinkByProto.pushLonk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_pushLonk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_pushLonk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025PushLinkByProto.proto\022\005proto\032\014Entity.p" +
      "roto\"p\n\010pushLonk\022\016\n\006userId\030\001 \001(\t\022\017\n\007pict" +
      "ure\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\t\022\021\n\tuserGrade" +
      "\030\004 \001(\005\022\014\n\004time\030\005 \001(\005\022\020\n\010streamId\030\006 \001(\tB " +
      "\n\036com.sencorsta.ids.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_pushLonk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_pushLonk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_pushLonk_descriptor,
        new String[] { "UserId", "Picture", "Nickname", "UserGrade", "Time", "StreamId", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
