// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReconnectionByProto.proto

package com.jk.jkproject.net.im.info;

public final class ReconnectionByProto {
  private ReconnectionByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReconnectionReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReconnectionReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 1;</code>
     */
    String getRoomId();
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomIdBytes();
  }
  /**
   * Protobuf type {@code proto.ReconnectionReq}
   */
  public  static final class ReconnectionReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReconnectionReq)
      ReconnectionReqOrBuilder {
    // Use ReconnectionReq.newBuilder() to construct.
    private ReconnectionReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReconnectionReq() {
      roomId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReconnectionReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              roomId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReconnectionByProto.internal_static_proto_ReconnectionReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReconnectionByProto.internal_static_proto_ReconnectionReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReconnectionByProto.ReconnectionReq.class, ReconnectionByProto.ReconnectionReq.Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private volatile Object roomId_;
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 1;</code>
     */
    public String getRoomId() {
      Object ref = roomId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *房间id
     * </pre>
     *
     * <code>optional string roomId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReconnectionByProto.ReconnectionReq)) {
        return super.equals(obj);
      }
      ReconnectionByProto.ReconnectionReq other = (ReconnectionByProto.ReconnectionReq) obj;

      boolean result = true;
      result = result && getRoomId()
          .equals(other.getRoomId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReconnectionByProto.ReconnectionReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReconnectionByProto.ReconnectionReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReconnectionReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReconnectionReq)
        ReconnectionByProto.ReconnectionReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReconnectionByProto.internal_static_proto_ReconnectionReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReconnectionByProto.internal_static_proto_ReconnectionReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReconnectionByProto.ReconnectionReq.class, ReconnectionByProto.ReconnectionReq.Builder.class);
      }

      // Construct using ReconnectionByProto.ReconnectionReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roomId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReconnectionByProto.internal_static_proto_ReconnectionReq_descriptor;
      }

      public ReconnectionByProto.ReconnectionReq getDefaultInstanceForType() {
        return ReconnectionByProto.ReconnectionReq.getDefaultInstance();
      }

      public ReconnectionByProto.ReconnectionReq build() {
        ReconnectionByProto.ReconnectionReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReconnectionByProto.ReconnectionReq buildPartial() {
        ReconnectionByProto.ReconnectionReq result = new ReconnectionByProto.ReconnectionReq(this);
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReconnectionByProto.ReconnectionReq) {
          return mergeFrom((ReconnectionByProto.ReconnectionReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReconnectionByProto.ReconnectionReq other) {
        if (other == ReconnectionByProto.ReconnectionReq.getDefaultInstance()) return this;
        if (!other.getRoomId().isEmpty()) {
          roomId_ = other.roomId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReconnectionByProto.ReconnectionReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReconnectionByProto.ReconnectionReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object roomId_ = "";
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 1;</code>
       */
      public String getRoomId() {
        Object ref = roomId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roomId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes() {
        Object ref = roomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 1;</code>
       */
      public Builder setRoomId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 1;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = getDefaultInstance().getRoomId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间id
       * </pre>
       *
       * <code>optional string roomId = 1;</code>
       */
      public Builder setRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ReconnectionReq)
    }

    // @@protoc_insertion_point(class_scope:proto.ReconnectionReq)
    private static final ReconnectionByProto.ReconnectionReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReconnectionByProto.ReconnectionReq();
    }

    public static ReconnectionByProto.ReconnectionReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReconnectionReq>
        PARSER = new com.google.protobuf.AbstractParser<ReconnectionReq>() {
      public ReconnectionReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReconnectionReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReconnectionReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReconnectionReq> getParserForType() {
      return PARSER;
    }

    public ReconnectionByProto.ReconnectionReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReconnectionResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReconnectionRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsg getMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsgOrBuilder getMsgOrBuilder();

    /**
     * <pre>
     *正面压注总数量
     * </pre>
     *
     * <code>optional int32 front = 2;</code>
     */
    int getFront();

    /**
     * <pre>
     *反面压注总数量
     * </pre>
     *
     * <code>optional int32 contrary = 3;</code>
     */
    int getContrary();

    /**
     * <pre>
     *最大竞猜数量
     * </pre>
     *
     * <code>optional int32 maxBet = 4;</code>
     */
    int getMaxBet();

    /**
     * <pre>
     *个人正面下注数量
     * </pre>
     *
     * <code>optional int32 frontBet = 5;</code>
     */
    int getFrontBet();

    /**
     * <pre>
     *个人反面下注数量
     * </pre>
     *
     * <code>optional int32 contraryBet = 6;</code>
     */
    int getContraryBet();

    /**
     * <pre>
     * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
     * </pre>
     *
     * <code>optional string stage = 7;</code>
     */
    String getStage();
    /**
     * <pre>
     * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
     * </pre>
     *
     * <code>optional string stage = 7;</code>
     */
    com.google.protobuf.ByteString
        getStageBytes();

    /**
     * <pre>
     * 当前倒计时时间
     * </pre>
     *
     * <code>optional int32 time = 8;</code>
     */
    int getTime();

    /**
     * <pre>
     * 我的钻石数量
     * </pre>
     *
     * <code>optional int32 money = 9;</code>
     */
    int getMoney();

    /**
     * <pre>
     *是否当天第一次打开 0 是 1 否
     * </pre>
     *
     * <code>optional int32 isFirstOpen = 10;</code>
     */
    int getIsFirstOpen();
  }
  /**
   * Protobuf type {@code proto.ReconnectionRes}
   */
  public  static final class ReconnectionRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReconnectionRes)
      ReconnectionResOrBuilder {
    // Use ReconnectionRes.newBuilder() to construct.
    private ReconnectionRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReconnectionRes() {
      front_ = 0;
      contrary_ = 0;
      maxBet_ = 0;
      frontBet_ = 0;
      contraryBet_ = 0;
      stage_ = "";
      time_ = 0;
      money_ = 0;
      isFirstOpen_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReconnectionRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Entity.ReturnMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(Entity.ReturnMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              front_ = input.readInt32();
              break;
            }
            case 24: {

              contrary_ = input.readInt32();
              break;
            }
            case 32: {

              maxBet_ = input.readInt32();
              break;
            }
            case 40: {

              frontBet_ = input.readInt32();
              break;
            }
            case 48: {

              contraryBet_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              stage_ = s;
              break;
            }
            case 64: {

              time_ = input.readInt32();
              break;
            }
            case 72: {

              money_ = input.readInt32();
              break;
            }
            case 80: {

              isFirstOpen_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReconnectionByProto.internal_static_proto_ReconnectionRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReconnectionByProto.internal_static_proto_ReconnectionRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReconnectionByProto.ReconnectionRes.class, ReconnectionByProto.ReconnectionRes.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private Entity.ReturnMsg msg_;
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsg getMsg() {
      return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    public static final int FRONT_FIELD_NUMBER = 2;
    private int front_;
    /**
     * <pre>
     *正面压注总数量
     * </pre>
     *
     * <code>optional int32 front = 2;</code>
     */
    public int getFront() {
      return front_;
    }

    public static final int CONTRARY_FIELD_NUMBER = 3;
    private int contrary_;
    /**
     * <pre>
     *反面压注总数量
     * </pre>
     *
     * <code>optional int32 contrary = 3;</code>
     */
    public int getContrary() {
      return contrary_;
    }

    public static final int MAXBET_FIELD_NUMBER = 4;
    private int maxBet_;
    /**
     * <pre>
     *最大竞猜数量
     * </pre>
     *
     * <code>optional int32 maxBet = 4;</code>
     */
    public int getMaxBet() {
      return maxBet_;
    }

    public static final int FRONTBET_FIELD_NUMBER = 5;
    private int frontBet_;
    /**
     * <pre>
     *个人正面下注数量
     * </pre>
     *
     * <code>optional int32 frontBet = 5;</code>
     */
    public int getFrontBet() {
      return frontBet_;
    }

    public static final int CONTRARYBET_FIELD_NUMBER = 6;
    private int contraryBet_;
    /**
     * <pre>
     *个人反面下注数量
     * </pre>
     *
     * <code>optional int32 contraryBet = 6;</code>
     */
    public int getContraryBet() {
      return contraryBet_;
    }

    public static final int STAGE_FIELD_NUMBER = 7;
    private volatile Object stage_;
    /**
     * <pre>
     * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
     * </pre>
     *
     * <code>optional string stage = 7;</code>
     */
    public String getStage() {
      Object ref = stage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
     * </pre>
     *
     * <code>optional string stage = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStageBytes() {
      Object ref = stage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 8;
    private int time_;
    /**
     * <pre>
     * 当前倒计时时间
     * </pre>
     *
     * <code>optional int32 time = 8;</code>
     */
    public int getTime() {
      return time_;
    }

    public static final int MONEY_FIELD_NUMBER = 9;
    private int money_;
    /**
     * <pre>
     * 我的钻石数量
     * </pre>
     *
     * <code>optional int32 money = 9;</code>
     */
    public int getMoney() {
      return money_;
    }

    public static final int ISFIRSTOPEN_FIELD_NUMBER = 10;
    private int isFirstOpen_;
    /**
     * <pre>
     *是否当天第一次打开 0 是 1 否
     * </pre>
     *
     * <code>optional int32 isFirstOpen = 10;</code>
     */
    public int getIsFirstOpen() {
      return isFirstOpen_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
      if (front_ != 0) {
        output.writeInt32(2, front_);
      }
      if (contrary_ != 0) {
        output.writeInt32(3, contrary_);
      }
      if (maxBet_ != 0) {
        output.writeInt32(4, maxBet_);
      }
      if (frontBet_ != 0) {
        output.writeInt32(5, frontBet_);
      }
      if (contraryBet_ != 0) {
        output.writeInt32(6, contraryBet_);
      }
      if (!getStageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stage_);
      }
      if (time_ != 0) {
        output.writeInt32(8, time_);
      }
      if (money_ != 0) {
        output.writeInt32(9, money_);
      }
      if (isFirstOpen_ != 0) {
        output.writeInt32(10, isFirstOpen_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      if (front_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, front_);
      }
      if (contrary_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contrary_);
      }
      if (maxBet_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, maxBet_);
      }
      if (frontBet_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, frontBet_);
      }
      if (contraryBet_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, contraryBet_);
      }
      if (!getStageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, stage_);
      }
      if (time_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, time_);
      }
      if (money_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, money_);
      }
      if (isFirstOpen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, isFirstOpen_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReconnectionByProto.ReconnectionRes)) {
        return super.equals(obj);
      }
      ReconnectionByProto.ReconnectionRes other = (ReconnectionByProto.ReconnectionRes) obj;

      boolean result = true;
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && (getFront()
          == other.getFront());
      result = result && (getContrary()
          == other.getContrary());
      result = result && (getMaxBet()
          == other.getMaxBet());
      result = result && (getFrontBet()
          == other.getFrontBet());
      result = result && (getContraryBet()
          == other.getContraryBet());
      result = result && getStage()
          .equals(other.getStage());
      result = result && (getTime()
          == other.getTime());
      result = result && (getMoney()
          == other.getMoney());
      result = result && (getIsFirstOpen()
          == other.getIsFirstOpen());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (37 * hash) + FRONT_FIELD_NUMBER;
      hash = (53 * hash) + getFront();
      hash = (37 * hash) + CONTRARY_FIELD_NUMBER;
      hash = (53 * hash) + getContrary();
      hash = (37 * hash) + MAXBET_FIELD_NUMBER;
      hash = (53 * hash) + getMaxBet();
      hash = (37 * hash) + FRONTBET_FIELD_NUMBER;
      hash = (53 * hash) + getFrontBet();
      hash = (37 * hash) + CONTRARYBET_FIELD_NUMBER;
      hash = (53 * hash) + getContraryBet();
      hash = (37 * hash) + STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStage().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney();
      hash = (37 * hash) + ISFIRSTOPEN_FIELD_NUMBER;
      hash = (53 * hash) + getIsFirstOpen();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReconnectionByProto.ReconnectionRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReconnectionByProto.ReconnectionRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReconnectionByProto.ReconnectionRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReconnectionRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReconnectionRes)
        ReconnectionByProto.ReconnectionResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReconnectionByProto.internal_static_proto_ReconnectionRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReconnectionByProto.internal_static_proto_ReconnectionRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReconnectionByProto.ReconnectionRes.class, ReconnectionByProto.ReconnectionRes.Builder.class);
      }

      // Construct using ReconnectionByProto.ReconnectionRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        front_ = 0;

        contrary_ = 0;

        maxBet_ = 0;

        frontBet_ = 0;

        contraryBet_ = 0;

        stage_ = "";

        time_ = 0;

        money_ = 0;

        isFirstOpen_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReconnectionByProto.internal_static_proto_ReconnectionRes_descriptor;
      }

      public ReconnectionByProto.ReconnectionRes getDefaultInstanceForType() {
        return ReconnectionByProto.ReconnectionRes.getDefaultInstance();
      }

      public ReconnectionByProto.ReconnectionRes build() {
        ReconnectionByProto.ReconnectionRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReconnectionByProto.ReconnectionRes buildPartial() {
        ReconnectionByProto.ReconnectionRes result = new ReconnectionByProto.ReconnectionRes(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.front_ = front_;
        result.contrary_ = contrary_;
        result.maxBet_ = maxBet_;
        result.frontBet_ = frontBet_;
        result.contraryBet_ = contraryBet_;
        result.stage_ = stage_;
        result.time_ = time_;
        result.money_ = money_;
        result.isFirstOpen_ = isFirstOpen_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReconnectionByProto.ReconnectionRes) {
          return mergeFrom((ReconnectionByProto.ReconnectionRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReconnectionByProto.ReconnectionRes other) {
        if (other == ReconnectionByProto.ReconnectionRes.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        if (other.getFront() != 0) {
          setFront(other.getFront());
        }
        if (other.getContrary() != 0) {
          setContrary(other.getContrary());
        }
        if (other.getMaxBet() != 0) {
          setMaxBet(other.getMaxBet());
        }
        if (other.getFrontBet() != 0) {
          setFrontBet(other.getFrontBet());
        }
        if (other.getContraryBet() != 0) {
          setContraryBet(other.getContraryBet());
        }
        if (!other.getStage().isEmpty()) {
          stage_ = other.stage_;
          onChanged();
        }
        if (other.getTime() != 0) {
          setTime(other.getTime());
        }
        if (other.getMoney() != 0) {
          setMoney(other.getMoney());
        }
        if (other.getIsFirstOpen() != 0) {
          setIsFirstOpen(other.getIsFirstOpen());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReconnectionByProto.ReconnectionRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReconnectionByProto.ReconnectionRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Entity.ReturnMsg msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> msgBuilder_;
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(
          Entity.ReturnMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder mergeMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              Entity.ReturnMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              Entity.ReturnMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      private int front_ ;
      /**
       * <pre>
       *正面压注总数量
       * </pre>
       *
       * <code>optional int32 front = 2;</code>
       */
      public int getFront() {
        return front_;
      }
      /**
       * <pre>
       *正面压注总数量
       * </pre>
       *
       * <code>optional int32 front = 2;</code>
       */
      public Builder setFront(int value) {
        
        front_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正面压注总数量
       * </pre>
       *
       * <code>optional int32 front = 2;</code>
       */
      public Builder clearFront() {
        
        front_ = 0;
        onChanged();
        return this;
      }

      private int contrary_ ;
      /**
       * <pre>
       *反面压注总数量
       * </pre>
       *
       * <code>optional int32 contrary = 3;</code>
       */
      public int getContrary() {
        return contrary_;
      }
      /**
       * <pre>
       *反面压注总数量
       * </pre>
       *
       * <code>optional int32 contrary = 3;</code>
       */
      public Builder setContrary(int value) {
        
        contrary_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *反面压注总数量
       * </pre>
       *
       * <code>optional int32 contrary = 3;</code>
       */
      public Builder clearContrary() {
        
        contrary_ = 0;
        onChanged();
        return this;
      }

      private int maxBet_ ;
      /**
       * <pre>
       *最大竞猜数量
       * </pre>
       *
       * <code>optional int32 maxBet = 4;</code>
       */
      public int getMaxBet() {
        return maxBet_;
      }
      /**
       * <pre>
       *最大竞猜数量
       * </pre>
       *
       * <code>optional int32 maxBet = 4;</code>
       */
      public Builder setMaxBet(int value) {
        
        maxBet_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最大竞猜数量
       * </pre>
       *
       * <code>optional int32 maxBet = 4;</code>
       */
      public Builder clearMaxBet() {
        
        maxBet_ = 0;
        onChanged();
        return this;
      }

      private int frontBet_ ;
      /**
       * <pre>
       *个人正面下注数量
       * </pre>
       *
       * <code>optional int32 frontBet = 5;</code>
       */
      public int getFrontBet() {
        return frontBet_;
      }
      /**
       * <pre>
       *个人正面下注数量
       * </pre>
       *
       * <code>optional int32 frontBet = 5;</code>
       */
      public Builder setFrontBet(int value) {
        
        frontBet_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *个人正面下注数量
       * </pre>
       *
       * <code>optional int32 frontBet = 5;</code>
       */
      public Builder clearFrontBet() {
        
        frontBet_ = 0;
        onChanged();
        return this;
      }

      private int contraryBet_ ;
      /**
       * <pre>
       *个人反面下注数量
       * </pre>
       *
       * <code>optional int32 contraryBet = 6;</code>
       */
      public int getContraryBet() {
        return contraryBet_;
      }
      /**
       * <pre>
       *个人反面下注数量
       * </pre>
       *
       * <code>optional int32 contraryBet = 6;</code>
       */
      public Builder setContraryBet(int value) {
        
        contraryBet_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *个人反面下注数量
       * </pre>
       *
       * <code>optional int32 contraryBet = 6;</code>
       */
      public Builder clearContraryBet() {
        
        contraryBet_ = 0;
        onChanged();
        return this;
      }

      private Object stage_ = "";
      /**
       * <pre>
       * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
       * </pre>
       *
       * <code>optional string stage = 7;</code>
       */
      public String getStage() {
        Object ref = stage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          stage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
       * </pre>
       *
       * <code>optional string stage = 7;</code>
       */
      public com.google.protobuf.ByteString
          getStageBytes() {
        Object ref = stage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
       * </pre>
       *
       * <code>optional string stage = 7;</code>
       */
      public Builder setStage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
       * </pre>
       *
       * <code>optional string stage = 7;</code>
       */
      public Builder clearStage() {
        
        stage_ = getDefaultInstance().getStage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前阶段  1  等待阶段 2 下注阶段  3 出奖阶段
       * </pre>
       *
       * <code>optional string stage = 7;</code>
       */
      public Builder setStageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stage_ = value;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <pre>
       * 当前倒计时时间
       * </pre>
       *
       * <code>optional int32 time = 8;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <pre>
       * 当前倒计时时间
       * </pre>
       *
       * <code>optional int32 time = 8;</code>
       */
      public Builder setTime(int value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前倒计时时间
       * </pre>
       *
       * <code>optional int32 time = 8;</code>
       */
      public Builder clearTime() {
        
        time_ = 0;
        onChanged();
        return this;
      }

      private int money_ ;
      /**
       * <pre>
       * 我的钻石数量
       * </pre>
       *
       * <code>optional int32 money = 9;</code>
       */
      public int getMoney() {
        return money_;
      }
      /**
       * <pre>
       * 我的钻石数量
       * </pre>
       *
       * <code>optional int32 money = 9;</code>
       */
      public Builder setMoney(int value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 我的钻石数量
       * </pre>
       *
       * <code>optional int32 money = 9;</code>
       */
      public Builder clearMoney() {
        
        money_ = 0;
        onChanged();
        return this;
      }

      private int isFirstOpen_ ;
      /**
       * <pre>
       *是否当天第一次打开 0 是 1 否
       * </pre>
       *
       * <code>optional int32 isFirstOpen = 10;</code>
       */
      public int getIsFirstOpen() {
        return isFirstOpen_;
      }
      /**
       * <pre>
       *是否当天第一次打开 0 是 1 否
       * </pre>
       *
       * <code>optional int32 isFirstOpen = 10;</code>
       */
      public Builder setIsFirstOpen(int value) {
        
        isFirstOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否当天第一次打开 0 是 1 否
       * </pre>
       *
       * <code>optional int32 isFirstOpen = 10;</code>
       */
      public Builder clearIsFirstOpen() {
        
        isFirstOpen_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ReconnectionRes)
    }

    // @@protoc_insertion_point(class_scope:proto.ReconnectionRes)
    private static final ReconnectionByProto.ReconnectionRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReconnectionByProto.ReconnectionRes();
    }

    public static ReconnectionByProto.ReconnectionRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReconnectionRes>
        PARSER = new com.google.protobuf.AbstractParser<ReconnectionRes>() {
      public ReconnectionRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReconnectionRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReconnectionRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReconnectionRes> getParserForType() {
      return PARSER;
    }

    public ReconnectionByProto.ReconnectionRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReconnectionReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReconnectionReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReconnectionRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReconnectionRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031ReconnectionByProto.proto\022\005proto\032\014Enti" +
      "ty.proto\"!\n\017ReconnectionReq\022\016\n\006roomId\030\001 " +
      "\001(\t\"\311\001\n\017ReconnectionRes\022\035\n\003msg\030\001 \001(\0132\020.p" +
      "roto.ReturnMsg\022\r\n\005front\030\002 \001(\005\022\020\n\010contrar" +
      "y\030\003 \001(\005\022\016\n\006maxBet\030\004 \001(\005\022\020\n\010frontBet\030\005 \001(" +
      "\005\022\023\n\013contraryBet\030\006 \001(\005\022\r\n\005stage\030\007 \001(\t\022\014\n" +
      "\004time\030\010 \001(\005\022\r\n\005money\030\t \001(\005\022\023\n\013isFirstOpe" +
      "n\030\n \001(\005B \n\036com.sencorsta.ids.common.prot" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_ReconnectionReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReconnectionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReconnectionReq_descriptor,
        new String[] { "RoomId", });
    internal_static_proto_ReconnectionRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ReconnectionRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReconnectionRes_descriptor,
        new String[] { "Msg", "Front", "Contrary", "MaxBet", "FrontBet", "ContraryBet", "Stage", "Time", "Money", "IsFirstOpen", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
