// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendTeamChatByProto.proto

package com.jk.jkproject.net.im.info;

public final class SendTeamChatByProto {
  private SendTeamChatByProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendTeamChatByProtoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SendTeamChatByProtoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string teamId = 1;</code>
     */
    String getTeamId();
    /**
     * <code>optional string teamId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTeamIdBytes();

    /**
     * <code>optional string message = 2;</code>
     */
    String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code proto.SendTeamChatByProtoReq}
   */
  public  static final class SendTeamChatByProtoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SendTeamChatByProtoReq)
      SendTeamChatByProtoReqOrBuilder {
    // Use SendTeamChatByProtoReq.newBuilder() to construct.
    private SendTeamChatByProtoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendTeamChatByProtoReq() {
      teamId_ = "";
      message_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SendTeamChatByProtoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              teamId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendTeamChatByProtoReq.class, Builder.class);
    }

    public static final int TEAMID_FIELD_NUMBER = 1;
    private volatile Object teamId_;
    /**
     * <code>optional string teamId = 1;</code>
     */
    public String getTeamId() {
      Object ref = teamId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        teamId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string teamId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTeamIdBytes() {
      Object ref = teamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        teamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTeamIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, teamId_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTeamIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, teamId_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SendTeamChatByProtoReq)) {
        return super.equals(obj);
      }
      SendTeamChatByProtoReq other = (SendTeamChatByProtoReq) obj;

      boolean result = true;
      result = result && getTeamId()
          .equals(other.getTeamId());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TEAMID_FIELD_NUMBER;
      hash = (53 * hash) + getTeamId().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SendTeamChatByProtoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendTeamChatByProtoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendTeamChatByProtoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendTeamChatByProtoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendTeamChatByProtoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendTeamChatByProtoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendTeamChatByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SendTeamChatByProtoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SendTeamChatByProtoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SendTeamChatByProtoReq)
        SendTeamChatByProtoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SendTeamChatByProtoReq.class, Builder.class);
      }

      // Construct using com.sencorsta.ids.common.proto.SendTeamChatByProto.SendTeamChatByProtoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        teamId_ = "";

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoReq_descriptor;
      }

      public SendTeamChatByProtoReq getDefaultInstanceForType() {
        return SendTeamChatByProtoReq.getDefaultInstance();
      }

      public SendTeamChatByProtoReq build() {
        SendTeamChatByProtoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SendTeamChatByProtoReq buildPartial() {
        SendTeamChatByProtoReq result = new SendTeamChatByProtoReq(this);
        result.teamId_ = teamId_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SendTeamChatByProtoReq) {
          return mergeFrom((SendTeamChatByProtoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SendTeamChatByProtoReq other) {
        if (other == SendTeamChatByProtoReq.getDefaultInstance()) return this;
        if (!other.getTeamId().isEmpty()) {
          teamId_ = other.teamId_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SendTeamChatByProtoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SendTeamChatByProtoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object teamId_ = "";
      /**
       * <code>optional string teamId = 1;</code>
       */
      public String getTeamId() {
        Object ref = teamId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          teamId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string teamId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTeamIdBytes() {
        Object ref = teamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          teamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string teamId = 1;</code>
       */
      public Builder setTeamId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        teamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string teamId = 1;</code>
       */
      public Builder clearTeamId() {

        teamId_ = getDefaultInstance().getTeamId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string teamId = 1;</code>
       */
      public Builder setTeamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        teamId_ = value;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {

        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SendTeamChatByProtoReq)
    }

    // @@protoc_insertion_point(class_scope:proto.SendTeamChatByProtoReq)
    private static final SendTeamChatByProtoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendTeamChatByProtoReq();
    }

    public static SendTeamChatByProtoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendTeamChatByProtoReq>
        PARSER = new com.google.protobuf.AbstractParser<SendTeamChatByProtoReq>() {
      public SendTeamChatByProtoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SendTeamChatByProtoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendTeamChatByProtoReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SendTeamChatByProtoReq> getParserForType() {
      return PARSER;
    }

    public SendTeamChatByProtoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendTeamChatByProtoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SendTeamChatByProtoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsg getMsg();
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    Entity.ReturnMsgOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code proto.SendTeamChatByProtoRes}
   */
  public  static final class SendTeamChatByProtoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SendTeamChatByProtoRes)
      SendTeamChatByProtoResOrBuilder {
    // Use SendTeamChatByProtoRes.newBuilder() to construct.
    private SendTeamChatByProtoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendTeamChatByProtoRes() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SendTeamChatByProtoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Entity.ReturnMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(Entity.ReturnMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendTeamChatByProtoRes.class, Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private Entity.ReturnMsg msg_;
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsg getMsg() {
      return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .proto.ReturnMsg msg = 1;</code>
     */
    public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SendTeamChatByProtoRes)) {
        return super.equals(obj);
      }
      SendTeamChatByProtoRes other = (SendTeamChatByProtoRes) obj;

      boolean result = true;
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SendTeamChatByProtoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendTeamChatByProtoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendTeamChatByProtoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendTeamChatByProtoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendTeamChatByProtoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendTeamChatByProtoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendTeamChatByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendTeamChatByProtoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SendTeamChatByProtoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SendTeamChatByProtoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SendTeamChatByProtoRes)
        SendTeamChatByProtoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SendTeamChatByProtoRes.class, Builder.class);
      }

      // Construct using com.sencorsta.ids.common.proto.SendTeamChatByProto.SendTeamChatByProtoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SendTeamChatByProto.internal_static_proto_SendTeamChatByProtoRes_descriptor;
      }

      public SendTeamChatByProtoRes getDefaultInstanceForType() {
        return SendTeamChatByProtoRes.getDefaultInstance();
      }

      public SendTeamChatByProtoRes build() {
        SendTeamChatByProtoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SendTeamChatByProtoRes buildPartial() {
        SendTeamChatByProtoRes result = new SendTeamChatByProtoRes(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SendTeamChatByProtoRes) {
          return mergeFrom((SendTeamChatByProtoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SendTeamChatByProtoRes other) {
        if (other == SendTeamChatByProtoRes.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SendTeamChatByProtoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SendTeamChatByProtoRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Entity.ReturnMsg msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder> msgBuilder_;
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? Entity.ReturnMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder setMsg(
          Entity.ReturnMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder mergeMsg(Entity.ReturnMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              Entity.ReturnMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsg.Builder getMsgBuilder() {

        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      public Entity.ReturnMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              Entity.ReturnMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .proto.ReturnMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entity.ReturnMsg, Entity.ReturnMsg.Builder, Entity.ReturnMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SendTeamChatByProtoRes)
    }

    // @@protoc_insertion_point(class_scope:proto.SendTeamChatByProtoRes)
    private static final SendTeamChatByProtoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendTeamChatByProtoRes();
    }

    public static SendTeamChatByProtoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendTeamChatByProtoRes>
        PARSER = new com.google.protobuf.AbstractParser<SendTeamChatByProtoRes>() {
      public SendTeamChatByProtoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SendTeamChatByProtoRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendTeamChatByProtoRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SendTeamChatByProtoRes> getParserForType() {
      return PARSER;
    }

    public SendTeamChatByProtoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SendTeamChatByProtoReq_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SendTeamChatByProtoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SendTeamChatByProtoRes_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SendTeamChatByProtoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031SendTeamChatByProto.proto\022\005proto\032\014Enti" +
      "ty.proto\"9\n\026SendTeamChatByProtoReq\022\016\n\006te" +
      "amId\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"7\n\026SendTeamC" +
      "hatByProtoRes\022\035\n\003msg\030\001 \001(\0132\020.proto.Retur" +
      "nMsgB \n\036com.sencorsta.ids.common.protob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Entity.getDescriptor(),
        }, assigner);
    internal_static_proto_SendTeamChatByProtoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SendTeamChatByProtoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SendTeamChatByProtoReq_descriptor,
        new String[] { "TeamId", "Message", });
    internal_static_proto_SendTeamChatByProtoRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SendTeamChatByProtoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SendTeamChatByProtoRes_descriptor,
        new String[] { "Msg", });
    Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
